const districtsAP = [
  {
    district_no: "AP-01",
    district_code: "ASR",
    district_name: "Alluri Sitharama Raju",
    state_no: 37,
  },
  {
    district_no: "AP-02",
    district_code: "AKP",
    district_name: "Anakapalli",
    state_no: 37,
  },
  {
    district_no: "AP-03",
    district_code: "ATP",
    district_name: "Ananthapuramu",
    state_no: 37,
  },
  {
    district_no: "AP-04",
    district_code: "ANM",
    district_name: "Annamayya",
    state_no: 37,
  },
  {
    district_no: "AP-05",
    district_code: "BPT",
    district_name: "Bapatla",
    state_no: 37,
  },
  {
    district_no: "AP-06",
    district_code: "CTR",
    district_name: "Chittoor",
    state_no: 37,
  },
  {
    district_no: "AP-07",
    district_code: "KNM",
    district_name: "Dr. B.R. Ambedkar Konaseema",
    state_no: 37,
  },
  {
    district_no: "AP-08",
    district_code: "EG",
    district_name: "East Godavari",
    state_no: 37,
  },
  {
    district_no: "AP-09",
    district_code: "ELR",
    district_name: "Eluru",
    state_no: 37,
  },
  {
    district_no: "AP-10",
    district_code: "GNT",
    district_name: "Guntur",
    state_no: 37,
  },
  {
    district_no: "AP-11",
    district_code: "KKN",
    district_name: "Kakinada",
    state_no: 37,
  },
  {
    district_no: "AP-12",
    district_code: "KRI",
    district_name: "Krishna",
    state_no: 37,
  },
  {
    district_no: "AP-13",
    district_code: "KRN",
    district_name: "Kurnool",
    state_no: 37,
  },
  {
    district_no: "AP-14",
    district_code: "NDL",
    district_name: "Nandyal",
    state_no: 37,
  },
  {
    district_no: "AP-15",
    district_code: "NTR",
    district_name: "NTR",
    state_no: 37,
  },
  {
    district_no: "AP-16",
    district_code: "PLN",
    district_name: "Palnadu",
    state_no: 37,
  },
  {
    district_no: "AP-17",
    district_code: "PPM",
    district_name: "Parvathipuram Manyam",
    state_no: 37,
  },
  {
    district_no: "AP-18",
    district_code: "PRK",
    district_name: "Prakasam",
    state_no: 37,
  },
  {
    district_no: "AP-19",
    district_code: "NLR",
    district_name: "SPSR Nellore",
    state_no: 37,
  },
  {
    district_no: "AP-20",
    district_code: "SSS",
    district_name: "Sri Sathya Sai",
    state_no: 37,
  },
  {
    district_no: "AP-21",
    district_code: "SRK",
    district_name: "Srikakulam",
    state_no: 37,
  },
  {
    district_no: "AP-22",
    district_code: "TPT",
    district_name: "Tirupati",
    state_no: 37,
  },
  {
    district_no: "AP-23",
    district_code: "VSP",
    district_name: "Visakhapatnam",
    state_no: 37,
  },
  {
    district_no: "AP-24",
    district_code: "VZM",
    district_name: "Vizianagaram",
    state_no: 37,
  },
  {
    district_no: "AP-25",
    district_code: "WG",
    district_name: "West Godavari",
    state_no: 37,
  },
  {
    district_no: "AP-26",
    district_code: "YSR",
    district_name: "Y.S.R. Kadapa",
    state_no: 37,
  },
];

const districtsAR = [
  {
    district_no: "AR-01",
    district_code: "ANJ",
    district_name: "Anjaw",
    state_no: 12,
  },
  {
    district_no: "AR-02",
    district_code: "BIC",
    district_name: "Bichom",
    state_no: 12,
  },
  {
    district_no: "AR-03",
    district_code: "CHA",
    district_name: "Changlang",
    state_no: 12,
  },
  {
    district_no: "AR-04",
    district_code: "DVA",
    district_name: "Dibang Valley",
    state_no: 12,
  },
  {
    district_no: "AR-05",
    district_code: "EKM",
    district_name: "East Kameng",
    state_no: 12,
  },
  {
    district_no: "AR-06",
    district_code: "ESI",
    district_name: "East Siang",
    state_no: 12,
  },
  {
    district_no: "AR-07",
    district_code: "ICC",
    district_name: "Itanagar Capital Complex",
    state_no: 12,
  },
  {
    district_no: "AR-08",
    district_code: "KAM",
    district_name: "Kamle",
    state_no: 12,
  },
  {
    district_no: "AR-09",
    district_code: "KPA",
    district_name: "Keyi Panyor",
    state_no: 12,
  },
  {
    district_no: "AR-10",
    district_code: "KDA",
    district_name: "Kra Daadi",
    state_no: 12,
  },
  {
    district_no: "AR-11",
    district_code: "KKU",
    district_name: "Kurung Kumey",
    state_no: 12,
  },
  {
    district_no: "AR-12",
    district_code: "LRA",
    district_name: "Lepa Rada",
    state_no: 12,
  },
  {
    district_no: "AR-13",
    district_code: "LOH",
    district_name: "Lohit",
    state_no: 12,
  },
  {
    district_no: "AR-14",
    district_code: "LON",
    district_name: "Longding",
    state_no: 12,
  },
  {
    district_no: "AR-15",
    district_code: "LDV",
    district_name: "Lower Dibang Valley",
    state_no: 12,
  },
  {
    district_no: "AR-16",
    district_code: "LSI",
    district_name: "Lower Siang",
    state_no: 12,
  },
  {
    district_no: "AR-17",
    district_code: "LSU",
    district_name: "Lower Subansiri",
    state_no: 12,
  },
  {
    district_no: "AR-18",
    district_code: "NAM",
    district_name: "Namsai",
    state_no: 12,
  },
  {
    district_no: "AR-19",
    district_code: "PKE",
    district_name: "Pakke Kessang",
    state_no: 12,
  },
  {
    district_no: "AR-20",
    district_code: "PPA",
    district_name: "Papum Pare",
    state_no: 12,
  },
  {
    district_no: "AR-21",
    district_code: "SYO",
    district_name: "Shi Yomi",
    state_no: 12,
  },
  {
    district_no: "AR-22",
    district_code: "SIA",
    district_name: "Siang",
    state_no: 12,
  },
  {
    district_no: "AR-23",
    district_code: "TAW",
    district_name: "Tawang",
    state_no: 12,
  },
  {
    district_no: "AR-24",
    district_code: "TIR",
    district_name: "Tirap",
    state_no: 12,
  },
  {
    district_no: "AR-25",
    district_code: "USI",
    district_name: "Upper Siang",
    state_no: 12,
  },
  {
    district_no: "AR-26",
    district_code: "USU",
    district_name: "Upper Subansiri",
    state_no: 12,
  },
  {
    district_no: "AR-27",
    district_code: "WKM",
    district_name: "West Kameng",
    state_no: 12,
  },
  {
    district_no: "AR-28",
    district_code: "WSI",
    district_name: "West Siang",
    state_no: 12,
  },
];

const districtsAS = [
  {
    district_no: "AS-01",
    district_code: "BKS",
    district_name: "Baksa",
    state_no: "18",
  },
  {
    district_no: "AS-02",
    district_code: "BJI",
    district_name: "Bajali",
    state_no: "18",
  },
  {
    district_no: "AS-03",
    district_code: "BRP",
    district_name: "Barpeta",
    state_no: "18",
  },
  {
    district_no: "AS-04",
    district_code: "BSN",
    district_name: "Biswanath",
    state_no: "18",
  },
  {
    district_no: "AS-05",
    district_code: "BON",
    district_name: "Bongaigaon",
    state_no: "18",
  },
  {
    district_no: "AS-06",
    district_code: "CAC",
    district_name: "Cachar",
    state_no: "18",
  },
  {
    district_no: "AS-07",
    district_code: "CHD",
    district_name: "Charaideo",
    state_no: "18",
  },
  {
    district_no: "AS-08",
    district_code: "CHI",
    district_name: "Chirang",
    state_no: "18",
  },
  {
    district_no: "AS-09",
    district_code: "DAR",
    district_name: "Darrang",
    state_no: "18",
  },
  {
    district_no: "AS-10",
    district_code: "DHE",
    district_name: "Dhemaji",
    state_no: "18",
  },
  {
    district_no: "AS-11",
    district_code: "DHU",
    district_name: "Dhubri",
    state_no: "18",
  },
  {
    district_no: "AS-12",
    district_code: "DIB",
    district_name: "Dibrugarh",
    state_no: "18",
  },
  {
    district_no: "AS-13",
    district_code: "DIH",
    district_name: "Dima Hasao",
    state_no: "18",
  },
  {
    district_no: "AS-14",
    district_code: "GOA",
    district_name: "Goalpara",
    state_no: "18",
  },
  {
    district_no: "AS-15",
    district_code: "GOL",
    district_name: "Golaghat",
    state_no: "18",
  },
  {
    district_no: "AS-16",
    district_code: "HAI",
    district_name: "Hailakandi",
    state_no: "18",
  },
  {
    district_no: "AS-17",
    district_code: "HOJ",
    district_name: "Hojai",
    state_no: "18",
  },
  {
    district_no: "AS-18",
    district_code: "JOR",
    district_name: "Jorhat",
    state_no: "18",
  },
  {
    district_no: "AS-19",
    district_code: "KAM",
    district_name: "Kamrup",
    state_no: "18",
  },
  {
    district_no: "AS-20",
    district_code: "KMM",
    district_name: "Kamrup Metropolitan",
    state_no: "18",
  },
  {
    district_no: "AS-21",
    district_code: "KBA",
    district_name: "Karbi Anglong",
    state_no: "18",
  },
  {
    district_no: "AS-22",
    district_code: "KAR",
    district_name: "Karimganj",
    state_no: "18",
  },
  {
    district_no: "AS-23",
    district_code: "KOK",
    district_name: "Kokrajhar",
    state_no: "18",
  },
  {
    district_no: "AS-24",
    district_code: "LAK",
    district_name: "Lakhimpur",
    state_no: "18",
  },
  {
    district_no: "AS-25",
    district_code: "MAJ",
    district_name: "Majuli",
    state_no: "18",
  },
  {
    district_no: "AS-26",
    district_code: "MOR",
    district_name: "Morigaon",
    state_no: "18",
  },
  {
    district_no: "AS-27",
    district_code: "NAG",
    district_name: "Nagaon",
    state_no: "18",
  },
  {
    district_no: "AS-28",
    district_code: "NAL",
    district_name: "Nalbari",
    state_no: "18",
  },
  {
    district_no: "AS-29",
    district_code: "SIV",
    district_name: "Sivasagar",
    state_no: "18",
  },
  {
    district_no: "AS-30",
    district_code: "SON",
    district_name: "Sonitpur",
    state_no: "18",
  },
  {
    district_no: "AS-31",
    district_code: "SSM",
    district_name: "South Salmara-Mankachar",
    state_no: "18",
  },
  {
    district_no: "AS-32",
    district_code: "TAM",
    district_name: "Tamulpur",
    state_no: "18",
  },
  {
    district_no: "AS-33",
    district_code: "TIN",
    district_name: "Tinsukia",
    state_no: "18",
  },
  {
    district_no: "AS-34",
    district_code: "UDA",
    district_name: "Udalguri",
    state_no: "18",
  },
  {
    district_no: "AS-35",
    district_code: "WKA",
    district_name: "West Karbi Anglong",
    state_no: "18",
  },
];

const districtsBR = [
  {
    district_no: "BR-01",
    district_code: "ARA",
    district_name: "Araria",
    state_no: "10",
  },
  {
    district_no: "BR-02",
    district_code: "ARW",
    district_name: "Arwal",
    state_no: "10",
  },
  {
    district_no: "BR-03",
    district_code: "AUR",
    district_name: "Aurangabad",
    state_no: "10",
  },
  {
    district_no: "BR-04",
    district_code: "BAN",
    district_name: "Banka",
    state_no: "10",
  },
  {
    district_no: "BR-05",
    district_code: "BEG",
    district_name: "Begusarai",
    state_no: "10",
  },
  {
    district_no: "BR-06",
    district_code: "BHA",
    district_name: "Bhagalpur",
    state_no: "10",
  },
  {
    district_no: "BR-07",
    district_code: "BHO",
    district_name: "Bhojpur",
    state_no: "10",
  },
  {
    district_no: "BR-08",
    district_code: "BUX",
    district_name: "Buxar",
    state_no: "10",
  },
  {
    district_no: "BR-09",
    district_code: "DAR",
    district_name: "Darbhanga",
    state_no: "10",
  },
  {
    district_no: "BR-10",
    district_code: "ECH",
    district_name: "East Champaran (Motihari)",
    state_no: "10",
  },
  {
    district_no: "BR-11",
    district_code: "GAY",
    district_name: "Gaya",
    state_no: "10",
  },
  {
    district_no: "BR-12",
    district_code: "GOP",
    district_name: "Gopalganj",
    state_no: "10",
  },
  {
    district_no: "BR-13",
    district_code: "JAM",
    district_name: "Jamui",
    state_no: "10",
  },
  {
    district_no: "BR-14",
    district_code: "JEH",
    district_name: "Jehanabad",
    state_no: "10",
  },
  {
    district_no: "BR-15",
    district_code: "KAI",
    district_name: "Kaimur (Bhabua)",
    state_no: "10",
  },
  {
    district_no: "BR-16",
    district_code: "KAT",
    district_name: "Katihar",
    state_no: "10",
  },
  {
    district_no: "BR-17",
    district_code: "KHA",
    district_name: "Khagaria",
    state_no: "10",
  },
  {
    district_no: "BR-18",
    district_code: "KIS",
    district_name: "Kishanganj",
    state_no: "10",
  },
  {
    district_no: "BR-19",
    district_code: "LAK",
    district_name: "Lakhisarai",
    state_no: "10",
  },
  {
    district_no: "BR-20",
    district_code: "MAD",
    district_name: "Madhepura",
    state_no: "10",
  },
  {
    district_no: "BR-21",
    district_code: "MDB",
    district_name: "Madhubani",
    state_no: "10",
  },
  {
    district_no: "BR-22",
    district_code: "MUN",
    district_name: "Munger",
    state_no: "10",
  },
  {
    district_no: "BR-23",
    district_code: "MUZ",
    district_name: "Muzaffarpur",
    state_no: "10",
  },
  {
    district_no: "BR-24",
    district_code: "NAL",
    district_name: "Nalanda",
    state_no: "10",
  },
  {
    district_no: "BR-25",
    district_code: "NAW",
    district_name: "Nawada",
    state_no: "10",
  },
  {
    district_no: "BR-26",
    district_code: "PAT",
    district_name: "Patna",
    state_no: "10",
  },
  {
    district_no: "BR-27",
    district_code: "PUR",
    district_name: "Purnia",
    state_no: "10",
  },
  {
    district_no: "BR-28",
    district_code: "ROH",
    district_name: "Rohtas",
    state_no: "10",
  },
  {
    district_no: "BR-29",
    district_code: "SAH",
    district_name: "Saharsa",
    state_no: "10",
  },
  {
    district_no: "BR-30",
    district_code: "SAM",
    district_name: "Samastipur",
    state_no: "10",
  },
  {
    district_no: "BR-31",
    district_code: "SAR",
    district_name: "Saran",
    state_no: "10",
  },
  {
    district_no: "BR-32",
    district_code: "SHE",
    district_name: "Sheikhpura",
    state_no: "10",
  },
  {
    district_no: "BR-33",
    district_code: "SHR",
    district_name: "Sheohar",
    state_no: "10",
  },
  {
    district_no: "BR-34",
    district_code: "SIT",
    district_name: "Sitamarhi",
    state_no: "10",
  },
  {
    district_no: "BR-35",
    district_code: "SIW",
    district_name: "Siwan",
    state_no: "10",
  },
  {
    district_no: "BR-36",
    district_code: "SUP",
    district_name: "Supaul",
    state_no: "10",
  },
  {
    district_no: "BR-37",
    district_code: "VAI",
    district_name: "Vaishali",
    state_no: "10",
  },
  {
    district_no: "BR-38",
    district_code: "WCH",
    district_name: "West Champaran",
    state_no: "10",
  },
];

const districtsCG = [
  {
    district_no: "CG-01",
    district_code: "BAL",
    district_name: "Balod",
    state_no: "22",
  },
  {
    district_no: "CG-02",
    district_code: "BBZ",
    district_name: "Baloda Bazar",
    state_no: "22",
  },
  {
    district_no: "CG-03",
    district_code: "BRP",
    district_name: "Balrampur",
    state_no: "22",
  },
  {
    district_no: "CG-04",
    district_code: "BAS",
    district_name: "Bastar",
    state_no: "22",
  },
  {
    district_no: "CG-05",
    district_code: "BEM",
    district_name: "Bemetara",
    state_no: "22",
  },
  {
    district_no: "CG-06",
    district_code: "BIJ",
    district_name: "Bijapur",
    state_no: "22",
  },
  {
    district_no: "CG-07",
    district_code: "BIL",
    district_name: "Bilaspur",
    state_no: "22",
  },
  {
    district_no: "CG-08",
    district_code: "DAN",
    district_name: "Dantewada",
    state_no: "22",
  },
  {
    district_no: "CG-09",
    district_code: "DHA",
    district_name: "Dhamtari",
    state_no: "22",
  },
  {
    district_no: "CG-10",
    district_code: "DUR",
    district_name: "Durg",
    state_no: "22",
  },
  {
    district_no: "CG-11",
    district_code: "GAR",
    district_name: "Gariaband",
    state_no: "22",
  },
  {
    district_no: "CG-12",
    district_code: "GPM",
    district_name: "Gaurela-Pendra-Marwahi",
    state_no: "22",
  },
  {
    district_no: "CG-13",
    district_code: "JAC",
    district_name: "Janjgir-Champa",
    state_no: "22",
  },
  {
    district_no: "CG-14",
    district_code: "JAS",
    district_name: "Jashpur",
    state_no: "22",
  },
  {
    district_no: "CG-15",
    district_code: "KAB",
    district_name: "Kabirdham",
    state_no: "22",
  },
  {
    district_no: "CG-16",
    district_code: "KAN",
    district_name: "Kanker",
    state_no: "22",
  },
  {
    district_no: "CG-17",
    district_code: "KON",
    district_name: "Kondagaon",
    state_no: "22",
  },
  {
    district_no: "CG-18",
    district_code: "KOR",
    district_name: "Korba",
    state_no: "22",
  },
  {
    district_no: "CG-19",
    district_code: "KRY",
    district_name: "Koriya",
    state_no: "22",
  },
  {
    district_no: "CG-20",
    district_code: "MAH",
    district_name: "Mahasamund",
    state_no: "22",
  },
  {
    district_no: "CG-21",
    district_code: "MCB",
    district_name: "Manendragarh-Chirmiri-Bharatpur",
    state_no: "22",
  },
  {
    district_no: "CG-22",
    district_code: "MMA",
    district_name: "Mohla-Manpur-Ambagarh Chowki",
    state_no: "22",
  },
  {
    district_no: "CG-23",
    district_code: "MUN",
    district_name: "Mungeli",
    state_no: "22",
  },
  {
    district_no: "CG-24",
    district_code: "NAR",
    district_name: "Narayanpur",
    state_no: "22",
  },
  {
    district_no: "CG-25",
    district_code: "RAI",
    district_name: "Raigarh",
    state_no: "22",
  },
  {
    district_no: "CG-26",
    district_code: "RAP",
    district_name: "Raipur",
    state_no: "22",
  },
  {
    district_no: "CG-27",
    district_code: "RJN",
    district_name: "Rajnandgaon",
    state_no: "22",
  },
  {
    district_no: "CG-28",
    district_code: "SAB",
    district_name: "Sarangarh-Bilaigarh",
    state_no: "22",
  },
  {
    district_no: "CG-29",
    district_code: "SUK",
    district_name: "Sukma",
    state_no: "22",
  },
  {
    district_no: "CG-30",
    district_code: "SUR",
    district_name: "Surajpur",
    state_no: "22",
  },
  {
    district_no: "CG-31",
    district_code: "SRG",
    district_name: "Surguja",
    state_no: "22",
  },
  {
    district_no: "CG-32",
    district_code: "SAK",
    district_name: "Sakti",
    state_no: "22",
  },
  {
    district_no: "CG-33",
    district_code: "KCG",
    district_name: "Khairagarh-Chhuikhadan-Gandai",
    state_no: "22",
  },
];

const districtsGA = [
  {
    district_no: "GA-01",
    district_code: "NGO",
    district_name: "North Goa",
    state_no: "30",
  },
  {
    district_no: "GA-02",
    district_code: "SGO",
    district_name: "South Goa",
    state_no: "30",
  },
];

const districtsGJ = [
  {
    district_no: "GJ-01",
    district_code: "AHM",
    district_name: "Ahmedabad",
    state_no: "24",
  },
  {
    district_no: "GJ-02",
    district_code: "AMR",
    district_name: "Amreli",
    state_no: "24",
  },
  {
    district_no: "GJ-03",
    district_code: "ANA",
    district_name: "Anand",
    state_no: "24",
  },
  {
    district_no: "GJ-04",
    district_code: "ARA",
    district_name: "Aravalli",
    state_no: "24",
  },
  {
    district_no: "GJ-05",
    district_code: "BAN",
    district_name: "Banaskantha",
    state_no: "24",
  },
  {
    district_no: "GJ-06",
    district_code: "BHA",
    district_name: "Bharuch",
    state_no: "24",
  },
  {
    district_no: "GJ-07",
    district_code: "BHV",
    district_name: "Bhavnagar",
    state_no: "24",
  },
  {
    district_no: "GJ-08",
    district_code: "BOT",
    district_name: "Botad",
    state_no: "24",
  },
  {
    district_no: "GJ-09",
    district_code: "CHU",
    district_name: "Chhota Udaipur",
    state_no: "24",
  },
  {
    district_no: "GJ-10",
    district_code: "DAH",
    district_name: "Dahod",
    state_no: "24",
  },
  {
    district_no: "GJ-11",
    district_code: "DAN",
    district_name: "Dang",
    state_no: "24",
  },
  {
    district_no: "GJ-12",
    district_code: "DED",
    district_name: "Devbhoomi Dwarka",
    state_no: "24",
  },
  {
    district_no: "GJ-13",
    district_code: "GAN",
    district_name: "Gandhinagar",
    state_no: "24",
  },
  {
    district_no: "GJ-14",
    district_code: "GIS",
    district_name: "Gir Somnath",
    state_no: "24",
  },
  {
    district_no: "GJ-15",
    district_code: "JAM",
    district_name: "Jamnagar",
    state_no: "24",
  },
  {
    district_no: "GJ-16",
    district_code: "JUN",
    district_name: "Junagadh",
    state_no: "24",
  },
  {
    district_no: "GJ-17",
    district_code: "KHE",
    district_name: "Kheda",
    state_no: "24",
  },
  {
    district_no: "GJ-18",
    district_code: "KUT",
    district_name: "Kutch",
    state_no: "24",
  },
  {
    district_no: "GJ-19",
    district_code: "MAH",
    district_name: "Mahisagar",
    state_no: "24",
  },
  {
    district_no: "GJ-20",
    district_code: "MEH",
    district_name: "Mehsana",
    state_no: "24",
  },
  {
    district_no: "GJ-21",
    district_code: "MOR",
    district_name: "Morbi",
    state_no: "24",
  },
  {
    district_no: "GJ-22",
    district_code: "NAR",
    district_name: "Narmada",
    state_no: "24",
  },
  {
    district_no: "GJ-23",
    district_code: "NAV",
    district_name: "Navsari",
    state_no: "24",
  },
  {
    district_no: "GJ-24",
    district_code: "PAN",
    district_name: "Panchmahal",
    state_no: "24",
  },
  {
    district_no: "GJ-25",
    district_code: "PAT",
    district_name: "Patan",
    state_no: "24",
  },
  {
    district_no: "GJ-26",
    district_code: "POR",
    district_name: "Porbandar",
    state_no: "24",
  },
  {
    district_no: "GJ-27",
    district_code: "RAK",
    district_name: "Rajkot",
    state_no: "24",
  },
  {
    district_no: "GJ-28",
    district_code: "SAB",
    district_name: "Sabarkantha",
    state_no: "24",
  },
  {
    district_no: "GJ-29",
    district_code: "SUR",
    district_name: "Surat",
    state_no: "24",
  },
  {
    district_no: "GJ-30",
    district_code: "SND",
    district_name: "Surendranagar",
    state_no: "24",
  },
  {
    district_no: "GJ-31",
    district_code: "TAP",
    district_name: "Tapi",
    state_no: "24",
  },
  {
    district_no: "GJ-32",
    district_code: "VAD",
    district_name: "Vadodara",
    state_no: "24",
  },
  {
    district_no: "GJ-33",
    district_code: "VAL",
    district_name: "Valsad",
    state_no: "24",
  },
];

const districtsHR = [
  {
    district_no: "HR-01",
    district_code: "AMB",
    district_name: "Ambala",
    state_no: "06",
  },
  {
    district_no: "HR-02",
    district_code: "BHI",
    district_name: "Bhiwani",
    state_no: "06",
  },
  {
    district_no: "HR-03",
    district_code: "CHD",
    district_name: "Charkhi Dadri",
    state_no: "06",
  },
  {
    district_no: "HR-04",
    district_code: "FAR",
    district_name: "Faridabad",
    state_no: "06",
  },
  {
    district_no: "HR-05",
    district_code: "FAT",
    district_name: "Fatehabad",
    state_no: "06",
  },
  {
    district_no: "HR-06",
    district_code: "GUR",
    district_name: "Gurugram",
    state_no: "06",
  },
  {
    district_no: "HR-07",
    district_code: "HIS",
    district_name: "Hisar",
    state_no: "06",
  },
  {
    district_no: "HR-08",
    district_code: "JHA",
    district_name: "Jhajjar",
    state_no: "06",
  },
  {
    district_no: "HR-09",
    district_code: "JIN",
    district_name: "Jind",
    state_no: "06",
  },
  {
    district_no: "HR-10",
    district_code: "KAI",
    district_name: "Kaithal",
    state_no: "06",
  },
  {
    district_no: "HR-11",
    district_code: "KAR",
    district_name: "Karnal",
    state_no: "06",
  },
  {
    district_no: "HR-12",
    district_code: "KUR",
    district_name: "Kurukshetra",
    state_no: "06",
  },
  {
    district_no: "HR-13",
    district_code: "MAH",
    district_name: "Mahendragarh",
    state_no: "06",
  },
  {
    district_no: "HR-14",
    district_code: "NUH",
    district_name: "Nuh",
    state_no: "06",
  },
  {
    district_no: "HR-15",
    district_code: "PAL",
    district_name: "Palwal",
    state_no: "06",
  },
  {
    district_no: "HR-16",
    district_code: "PNC",
    district_name: "Panchkula",
    state_no: "06",
  },
  {
    district_no: "HR-17",
    district_code: "PAN",
    district_name: "Panipat",
    state_no: "06",
  },
  {
    district_no: "HR-18",
    district_code: "REW",
    district_name: "Rewari",
    state_no: "06",
  },
  {
    district_no: "HR-19",
    district_code: "ROH",
    district_name: "Rohtak",
    state_no: "06",
  },
  {
    district_no: "HR-20",
    district_code: "SIR",
    district_name: "Sirsa",
    state_no: "06",
  },
  {
    district_no: "HR-21",
    district_code: "SON",
    district_name: "Sonipat",
    state_no: "06",
  },
  {
    district_no: "HR-22",
    district_code: "YAM",
    district_name: "Yamunanagar",
    state_no: "06",
  },
];

const districtsHP = [
  {
    district_no: "HP-01",
    district_code: "BIL",
    district_name: "Bilaspur",
    state_no: "02",
  },
  {
    district_no: "HP-02",
    district_code: "CHA",
    district_name: "Chamba",
    state_no: "02",
  },
  {
    district_no: "HP-03",
    district_code: "HAM",
    district_name: "Hamirpur",
    state_no: "02",
  },
  {
    district_no: "HP-04",
    district_code: "KAN",
    district_name: "Kangra",
    state_no: "02",
  },
  {
    district_no: "HP-05",
    district_code: "KIN",
    district_name: "Kinnaur",
    state_no: "02",
  },
  {
    district_no: "HP-06",
    district_code: "KUL",
    district_name: "Kullu",
    state_no: "02",
  },
  {
    district_no: "HP-07",
    district_code: "LAS",
    district_name: "Lahaul and Spiti",
    state_no: "02",
  },
  {
    district_no: "HP-08",
    district_code: "MAN",
    district_name: "Mandi",
    state_no: "02",
  },
  {
    district_no: "HP-09",
    district_code: "SHI",
    district_name: "Shimla",
    state_no: "02",
  },
  {
    district_no: "HP-10",
    district_code: "SIR",
    district_name: "Sirmaur",
    state_no: "02",
  },
  {
    district_no: "HP-11",
    district_code: "SOL",
    district_name: "Solan",
    state_no: "02",
  },
  {
    district_no: "HP-12",
    district_code: "UNA",
    district_name: "Una",
    state_no: "02",
  },
];

const districtsJH = [
  {
    district_no: "JH-01",
    district_code: "BOK",
    district_name: "Bokaro",
    state_no: "20",
  },
  {
    district_no: "JH-02",
    district_code: "CHT",
    district_name: "Chatra",
    state_no: "20",
  },
  {
    district_no: "JH-03",
    district_code: "DEO",
    district_name: "Deoghar",
    state_no: "20",
  },
  {
    district_no: "JH-04",
    district_code: "DHN",
    district_name: "Dhanbad",
    state_no: "20",
  },
  {
    district_no: "JH-05",
    district_code: "DUM",
    district_name: "Dumka",
    state_no: "20",
  },
  {
    district_no: "JH-06",
    district_code: "ESI",
    district_name: "East Singhbhum",
    state_no: "20",
  },
  {
    district_no: "JH-07",
    district_code: "GAR",
    district_name: "Garhwa",
    state_no: "20",
  },
  {
    district_no: "JH-08",
    district_code: "GIR",
    district_name: "Giridih",
    state_no: "20",
  },
  {
    district_no: "JH-09",
    district_code: "GOD",
    district_name: "Godda",
    state_no: "20",
  },
  {
    district_no: "JH-10",
    district_code: "GUM",
    district_name: "Gumla",
    state_no: "20",
  },
  {
    district_no: "JH-11",
    district_code: "HAZ",
    district_name: "Hazaribagh",
    state_no: "20",
  },
  {
    district_no: "JH-12",
    district_code: "JAM",
    district_name: "Jamtara",
    state_no: "20",
  },
  {
    district_no: "JH-13",
    district_code: "KHU",
    district_name: "Khunti",
    state_no: "20",
  },
  {
    district_no: "JH-14",
    district_code: "KOD",
    district_name: "Koderma",
    state_no: "20",
  },
  {
    district_no: "JH-15",
    district_code: "LAT",
    district_name: "Latehar",
    state_no: "20",
  },
  {
    district_no: "JH-16",
    district_code: "LOH",
    district_name: "Lohardaga",
    state_no: "20",
  },
  {
    district_no: "JH-17",
    district_code: "PAK",
    district_name: "Pakur",
    state_no: "20",
  },
  {
    district_no: "JH-18",
    district_code: "PAL",
    district_name: "Palamu",
    state_no: "20",
  },
  {
    district_no: "JH-19",
    district_code: "RAM",
    district_name: "Ramgarh",
    state_no: "20",
  },
  {
    district_no: "JH-20",
    district_code: "RAN",
    district_name: "Ranchi",
    state_no: "20",
  },
  {
    district_no: "JH-21",
    district_code: "SAH",
    district_name: "Sahibganj",
    state_no: "20",
  },
  {
    district_no: "JH-22",
    district_code: "SKH",
    district_name: "Seraikela Kharsawan",
    state_no: "20",
  },
  {
    district_no: "JH-23",
    district_code: "SIM",
    district_name: "Simdega",
    state_no: "20",
  },
  {
    district_no: "JH-24",
    district_code: "WSI",
    district_name: "West Singhbhum",
    state_no: "20",
  },
];

const districtsKA = [
  {
    district_no: "KA-01",
    district_code: "BGK",
    district_name: "Bagalkot",
    state_no: "29",
  },
  {
    district_no: "KA-02",
    district_code: "BAL",
    district_name: "Ballari",
    state_no: "29",
  },
  {
    district_no: "KA-03",
    district_code: "BEL",
    district_name: "Belagavi",
    state_no: "29",
  },
  {
    district_no: "KA-04",
    district_code: "BMR",
    district_name: "Bengaluru Rural",
    state_no: "29",
  },
  {
    district_no: "KA-05",
    district_code: "BMU",
    district_name: "Bengaluru Urban",
    state_no: "29",
  },
  {
    district_no: "KA-06",
    district_code: "BID",
    district_name: "Bidar",
    state_no: "29",
  },
  {
    district_no: "KA-07",
    district_code: "CJM",
    district_name: "Chamarajanagar",
    state_no: "29",
  },
  {
    district_no: "KA-08",
    district_code: "CKB",
    district_name: "Chikkaballapur",
    state_no: "29",
  },
  {
    district_no: "KA-09",
    district_code: "CKM",
    district_name: "Chikkamagaluru",
    state_no: "29",
  },
  {
    district_no: "KA-10",
    district_code: "CTD",
    district_name: "Chitradurga",
    state_no: "29",
  },
  {
    district_no: "KA-11",
    district_code: "DKN",
    district_name: "Dakshina Kannada",
    state_no: "29",
  },
  {
    district_no: "KA-12",
    district_code: "DAV",
    district_name: "Davanagere",
    state_no: "29",
  },
  {
    district_no: "KA-13",
    district_code: "DHA",
    district_name: "Dharwad",
    state_no: "29",
  },
  {
    district_no: "KA-14",
    district_code: "GAD",
    district_name: "Gadag",
    state_no: "29",
  },
  {
    district_no: "KA-15",
    district_code: "HAS",
    district_name: "Hassan",
    state_no: "29",
  },
  {
    district_no: "KA-16",
    district_code: "HAV",
    district_name: "Haveri",
    state_no: "29",
  },
  {
    district_no: "KA-17",
    district_code: "KAL",
    district_name: "Kalaburagi",
    state_no: "29",
  },
  {
    district_no: "KA-18",
    district_code: "KOD",
    district_name: "Kodagu",
    state_no: "29",
  },
  {
    district_no: "KA-19",
    district_code: "KOL",
    district_name: "Kolar",
    state_no: "29",
  },
  {
    district_no: "KA-20",
    district_code: "KOP",
    district_name: "Koppal",
    state_no: "29",
  },
  {
    district_no: "KA-21",
    district_code: "MAN",
    district_name: "Mandya",
    state_no: "29",
  },
  {
    district_no: "KA-22",
    district_code: "MYS",
    district_name: "Mysuru",
    state_no: "29",
  },
  {
    district_no: "KA-23",
    district_code: "RAI",
    district_name: "Raichur",
    state_no: "29",
  },
  {
    district_no: "KA-24",
    district_code: "RAM",
    district_name: "Ramanagara",
    state_no: "29",
  },
  {
    district_no: "KA-25",
    district_code: "SHI",
    district_name: "Shivamogga",
    state_no: "29",
  },
  {
    district_no: "KA-26",
    district_code: "TUM",
    district_name: "Tumakuru",
    state_no: "29",
  },
  {
    district_no: "KA-27",
    district_code: "UDU",
    district_name: "Udupi",
    state_no: "29",
  },
  {
    district_no: "KA-28",
    district_code: "UKN",
    district_name: "Uttara Kannada",
    state_no: "29",
  },
  {
    district_no: "KA-29",
    district_code: "VJN",
    district_name: "Vijayanagara",
    state_no: "29",
  },
  {
    district_no: "KA-30",
    district_code: "VJP",
    district_name: "Vijayapura",
    state_no: "29",
  },
  {
    district_no: "KA-31",
    district_code: "YAD",
    district_name: "Yadgir",
    state_no: "29",
  },
];

const districtsKL = [
  {
    district_no: "KL-01",
    district_code: "ALP",
    district_name: "Alappuzha",
    state_no: "32",
  },
  {
    district_no: "KL-02",
    district_code: "ERN",
    district_name: "Ernakulam",
    state_no: "32",
  },
  {
    district_no: "KL-03",
    district_code: "IDU",
    district_name: "Idukki",
    state_no: "32",
  },
  {
    district_no: "KL-04",
    district_code: "KAN",
    district_name: "Kannur",
    state_no: "32",
  },
  {
    district_no: "KL-05",
    district_code: "KAS",
    district_name: "Kasaragod",
    state_no: "32",
  },
  {
    district_no: "KL-06",
    district_code: "KOL",
    district_name: "Kollam",
    state_no: "32",
  },
  {
    district_no: "KL-07",
    district_code: "KOT",
    district_name: "Kottayam",
    state_no: "32",
  },
  {
    district_no: "KL-08",
    district_code: "KOZ",
    district_name: "Kozhikode",
    state_no: "32",
  },
  {
    district_no: "KL-09",
    district_code: "MAL",
    district_name: "Malappuram",
    state_no: "32",
  },
  {
    district_no: "KL-10",
    district_code: "PAL",
    district_name: "Palakkad",
    state_no: "32",
  },
  {
    district_no: "KL-11",
    district_code: "PAT",
    district_name: "Pathanamthitta",
    state_no: "32",
  },
  {
    district_no: "KL-12",
    district_code: "THI",
    district_name: "Thiruvananthapuram",
    state_no: "32",
  },
  {
    district_no: "KL-13",
    district_code: "THR",
    district_name: "Thrissur",
    state_no: "32",
  },
  {
    district_no: "KL-14",
    district_code: "WAY",
    district_name: "Wayanad",
    state_no: "32",
  },
];

const districtsMP = [
  {
    district_no: "MP-01",
    district_code: "AGM",
    district_name: "Agar Malwa",
    state_no: "23",
  },
  {
    district_no: "MP-02",
    district_code: "ALI",
    district_name: "Alirajpur",
    state_no: "23",
  },
  {
    district_no: "MP-03",
    district_code: "ANU",
    district_name: "Anuppur",
    state_no: "23",
  },
  {
    district_no: "MP-04",
    district_code: "ASH",
    district_name: "Ashoknagar",
    state_no: "23",
  },
  {
    district_no: "MP-05",
    district_code: "BAL",
    district_name: "Balaghat",
    state_no: "23",
  },
  {
    district_no: "MP-06",
    district_code: "BAR",
    district_name: "Barwani",
    state_no: "23",
  },
  {
    district_no: "MP-07",
    district_code: "BET",
    district_name: "Betul",
    state_no: "23",
  },
  {
    district_no: "MP-08",
    district_code: "BHI",
    district_name: "Bhind",
    state_no: "23",
  },
  {
    district_no: "MP-09",
    district_code: "BHO",
    district_name: "Bhopal",
    state_no: "23",
  },
  {
    district_no: "MP-10",
    district_code: "BUR",
    district_name: "Burhanpur",
    state_no: "23",
  },
  {
    district_no: "MP-11",
    district_code: "CHT",
    district_name: "Chhatarpur",
    state_no: "23",
  },
  {
    district_no: "MP-12",
    district_code: "CHH",
    district_name: "Chhindwara",
    state_no: "23",
  },
  {
    district_no: "MP-13",
    district_code: "DAM",
    district_name: "Damoh",
    state_no: "23",
  },
  {
    district_no: "MP-14",
    district_code: "DAT",
    district_name: "Datia",
    state_no: "23",
  },
  {
    district_no: "MP-15",
    district_code: "DEW",
    district_name: "Dewas",
    state_no: "23",
  },
  {
    district_no: "MP-16",
    district_code: "DHA",
    district_name: "Dhar",
    state_no: "23",
  },
  {
    district_no: "MP-17",
    district_code: "DIN",
    district_name: "Dindori",
    state_no: "23",
  },
  {
    district_no: "MP-18",
    district_code: "GUN",
    district_name: "Guna",
    state_no: "23",
  },
  {
    district_no: "MP-19",
    district_code: "GWA",
    district_name: "Gwalior",
    state_no: "23",
  },
  {
    district_no: "MP-20",
    district_code: "HAR",
    district_name: "Harda",
    state_no: "23",
  },
  {
    district_no: "MP-21",
    district_code: "IND",
    district_name: "Indore",
    state_no: "23",
  },
  {
    district_no: "MP-22",
    district_code: "JAB",
    district_name: "Jabalpur",
    state_no: "23",
  },
  {
    district_no: "MP-23",
    district_code: "JHA",
    district_name: "Jhabua",
    state_no: "23",
  },
  {
    district_no: "MP-24",
    district_code: "KAT",
    district_name: "Katni",
    state_no: "23",
  },
  {
    district_no: "MP-25",
    district_code: "KHA",
    district_name: "Khandwa",
    state_no: "23",
  },
  {
    district_no: "MP-26",
    district_code: "KHR",
    district_name: "Khargone",
    state_no: "23",
  },
  {
    district_no: "MP-27",
    district_code: "MAI",
    district_name: "Maihar",
    state_no: "23",
  },
  {
    district_no: "MP-28",
    district_code: "MAN",
    district_name: "Mandla",
    state_no: "23",
  },
  {
    district_no: "MP-29",
    district_code: "MDS",
    district_name: "Mandsaur",
    state_no: "23",
  },
  {
    district_no: "MP-30",
    district_code: "MAU",
    district_name: "Mauganj",
    state_no: "23",
  },
  {
    district_no: "MP-31",
    district_code: "MOR",
    district_name: "Morena",
    state_no: "23",
  },
  {
    district_no: "MP-32",
    district_code: "NRM",
    district_name: "Narmadapuram",
    state_no: "23",
  },
  {
    district_no: "MP-33",
    district_code: "NRS",
    district_name: "Narsinghpur",
    state_no: "23",
  },
  {
    district_no: "MP-34",
    district_code: "NEE",
    district_name: "Neemuch",
    state_no: "23",
  },
  {
    district_no: "MP-35",
    district_code: "NIW",
    district_name: "Niwari",
    state_no: "23",
  },
  {
    district_no: "MP-36",
    district_code: "PND",
    district_name: "Pandhurna",
    state_no: "23",
  },
  {
    district_no: "MP-37",
    district_code: "PAN",
    district_name: "Panna",
    state_no: "23",
  },
  {
    district_no: "MP-38",
    district_code: "RAI",
    district_name: "Raisen",
    state_no: "23",
  },
  {
    district_no: "MP-39",
    district_code: "RAJ",
    district_name: "Rajgarh",
    state_no: "23",
  },
  {
    district_no: "MP-40",
    district_code: "RAT",
    district_name: "Ratlam",
    state_no: "23",
  },
  {
    district_no: "MP-41",
    district_code: "REW",
    district_name: "Rewa",
    state_no: "23",
  },
  {
    district_no: "MP-42",
    district_code: "SAG",
    district_name: "Sagar",
    state_no: "23",
  },
  {
    district_no: "MP-43",
    district_code: "SAT",
    district_name: "Satna",
    state_no: "23",
  },
  {
    district_no: "MP-44",
    district_code: "SEH",
    district_name: "Sehore",
    state_no: "23",
  },
  {
    district_no: "MP-45",
    district_code: "SEO",
    district_name: "Seoni",
    state_no: "23",
  },
  {
    district_no: "MP-46",
    district_code: "SHA",
    district_name: "Shahdol",
    state_no: "23",
  },
  {
    district_no: "MP-47",
    district_code: "SJP",
    district_name: "Shajapur",
    state_no: "23",
  },
  {
    district_no: "MP-48",
    district_code: "SHE",
    district_name: "Sheopur",
    state_no: "23",
  },
  {
    district_no: "MP-49",
    district_code: "SHV",
    district_name: "Shivpuri",
    state_no: "23",
  },
  {
    district_no: "MP-50",
    district_code: "SID",
    district_name: "Sidhi",
    state_no: "23",
  },
  {
    district_no: "MP-51",
    district_code: "SIN",
    district_name: "Singrauli",
    state_no: "23",
  },
  {
    district_no: "MP-52",
    district_code: "TIK",
    district_name: "Tikamgarh",
    state_no: "23",
  },
  {
    district_no: "MP-53",
    district_code: "UJJ",
    district_name: "Ujjain",
    state_no: "23",
  },
  {
    district_no: "MP-54",
    district_code: "UMA",
    district_name: "Umaria",
    state_no: "23",
  },
  {
    district_no: "MP-55",
    district_code: "VID",
    district_name: "Vidisha",
    state_no: "23",
  },
];

const districtsMH = [
  {
    district_no: "MH-01",
    district_code: "AHM",
    district_name: "Ahmednagar",
    state_no: "27",
  },
  {
    district_no: "MH-02",
    district_code: "AKO",
    district_name: "Akola",
    state_no: "27",
  },
  {
    district_no: "MH-03",
    district_code: "AMR",
    district_name: "Amravati",
    state_no: "27",
  },
  {
    district_no: "MH-04",
    district_code: "BEE",
    district_name: "Beed",
    state_no: "27",
  },
  {
    district_no: "MH-05",
    district_code: "BHA",
    district_name: "Bhandara",
    state_no: "27",
  },
  {
    district_no: "MH-06",
    district_code: "BUL",
    district_name: "Buldhana",
    state_no: "27",
  },
  {
    district_no: "MH-07",
    district_code: "CHA",
    district_name: "Chandrapur",
    state_no: "27",
  },
  {
    district_no: "MH-08",
    district_code: "CSN",
    district_name: "Chhatrapati Sambhajinagar",
    state_no: "27",
  },
  {
    district_no: "MH-09",
    district_code: "DHR",
    district_name: "Dharashiv",
    state_no: "27",
  },
  {
    district_no: "MH-10",
    district_code: "DHU",
    district_name: "Dhule",
    state_no: "27",
  },
  {
    district_no: "MH-11",
    district_code: "GAD",
    district_name: "Gadchiroli",
    state_no: "27",
  },
  {
    district_no: "MH-12",
    district_code: "GON",
    district_name: "Gondia",
    state_no: "27",
  },
  {
    district_no: "MH-13",
    district_code: "HIN",
    district_name: "Hingoli",
    state_no: "27",
  },
  {
    district_no: "MH-14",
    district_code: "JAL",
    district_name: "Jalgaon",
    state_no: "27",
  },
  {
    district_no: "MH-15",
    district_code: "JLN",
    district_name: "Jalna",
    state_no: "27",
  },
  {
    district_no: "MH-16",
    district_code: "KOL",
    district_name: "Kolhapur",
    state_no: "27",
  },
  {
    district_no: "MH-17",
    district_code: "LAT",
    district_name: "Latur",
    state_no: "27",
  },
  {
    district_no: "MH-18",
    district_code: "MUM",
    district_name: "Mumbai City",
    state_no: "27",
  },
  {
    district_no: "MH-19",
    district_code: "MSU",
    district_name: "Mumbai Suburban",
    state_no: "27",
  },
  {
    district_no: "MH-20",
    district_code: "NAG",
    district_name: "Nagpur",
    state_no: "27",
  },
  {
    district_no: "MH-21",
    district_code: "NAN",
    district_name: "Nanded",
    state_no: "27",
  },
  {
    district_no: "MH-22",
    district_code: "NDB",
    district_name: "Nandurbar",
    state_no: "27",
  },
  {
    district_no: "MH-23",
    district_code: "NAS",
    district_name: "Nashik",
    state_no: "27",
  },
  {
    district_no: "MH-24",
    district_code: "PAL",
    district_name: "Palghar",
    state_no: "27",
  },
  {
    district_no: "MH-25",
    district_code: "PAR",
    district_name: "Parbhani",
    state_no: "27",
  },
  {
    district_no: "MH-26",
    district_code: "PUN",
    district_name: "Pune",
    state_no: "27",
  },
  {
    district_no: "MH-27",
    district_code: "RAI",
    district_name: "Raigad",
    state_no: "27",
  },
  {
    district_no: "MH-28",
    district_code: "RAT",
    district_name: "Ratnagiri",
    state_no: "27",
  },
  {
    district_no: "MH-29",
    district_code: "SAN",
    district_name: "Sangli",
    state_no: "27",
  },
  {
    district_no: "MH-30",
    district_code: "SAT",
    district_name: "Satara",
    state_no: "27",
  },
  {
    district_no: "MH-31",
    district_code: "SIN",
    district_name: "Sindhudurg",
    state_no: "27",
  },
  {
    district_no: "MH-32",
    district_code: "SOL",
    district_name: "Solapur",
    state_no: "27",
  },
  {
    district_no: "MH-33",
    district_code: "THA",
    district_name: "Thane",
    state_no: "27",
  },
  {
    district_no: "MH-34",
    district_code: "WAR",
    district_name: "Wardha",
    state_no: "27",
  },
  {
    district_no: "MH-35",
    district_code: "WAS",
    district_name: "Washim",
    state_no: "27",
  },
  {
    district_no: "MH-36",
    district_code: "YAV",
    district_name: "Yavatmal",
    state_no: "27",
  },
];

const districtsMN = [
  {
    district_no: "MN-01",
    district_code: "BPI",
    district_name: "Bishnupur",
    state_no: "14",
  },
  {
    district_no: "MN-02",
    district_code: "CDL",
    district_name: "Chandel",
    state_no: "14",
  },
  {
    district_no: "MN-03",
    district_code: "CCP",
    district_name: "Churachandpur",
    state_no: "14",
  },
  {
    district_no: "MN-04",
    district_code: "IME",
    district_name: "Imphal East",
    state_no: "14",
  },
  {
    district_no: "MN-05",
    district_code: "IMW",
    district_name: "Imphal West",
    state_no: "14",
  },
  {
    district_no: "MN-06",
    district_code: "JIR",
    district_name: "Jiribam",
    state_no: "14",
  },
  {
    district_no: "MN-07",
    district_code: "KAK",
    district_name: "Kakching",
    state_no: "14",
  },
  {
    district_no: "MN-08",
    district_code: "KAM",
    district_name: "Kamjong",
    state_no: "14",
  },
  {
    district_no: "MN-09",
    district_code: "KPI",
    district_name: "Kangpokpi",
    state_no: "14",
  },
  {
    district_no: "MN-10",
    district_code: "NON",
    district_name: "Noney",
    state_no: "14",
  },
  {
    district_no: "MN-11",
    district_code: "PZE",
    district_name: "Pherzawl",
    state_no: "14",
  },
  {
    district_no: "MN-12",
    district_code: "SEN",
    district_name: "Senapati",
    state_no: "14",
  },
  {
    district_no: "MN-13",
    district_code: "TML",
    district_name: "Tamenglong",
    state_no: "14",
  },
  {
    district_no: "MN-14",
    district_code: "TNL",
    district_name: "Tengnoupal",
    state_no: "14",
  },
  {
    district_no: "MN-15",
    district_code: "THO",
    district_name: "Thoubal",
    state_no: "14",
  },
  {
    district_no: "MN-16",
    district_code: "UKR",
    district_name: "Ukhrul",
    state_no: "14",
  },
];

const districtsML = [
  {
    district_no: "ML-01",
    district_code: "EGH",
    district_name: "East Garo Hills",
    state_no: "17",
  },
  {
    district_no: "ML-02",
    district_code: "EJH",
    district_name: "East Jaintia Hills",
    state_no: "17",
  },
  {
    district_no: "ML-03",
    district_code: "EKH",
    district_name: "East Khasi Hills",
    state_no: "17",
  },
  {
    district_no: "ML-04",
    district_code: "EWK",
    district_name: "Eastern West Khasi Hills",
    state_no: "17",
  },
  {
    district_no: "ML-05",
    district_code: "NGH",
    district_name: "North Garo Hills",
    state_no: "17",
  },
  {
    district_no: "ML-06",
    district_code: "RIB",
    district_name: "Ri Bhoi",
    state_no: "17",
  },
  {
    district_no: "ML-07",
    district_code: "SGH",
    district_name: "South Garo Hills",
    state_no: "17",
  },
  {
    district_no: "ML-08",
    district_code: "SWG",
    district_name: "South West Garo Hills",
    state_no: "17",
  },
  {
    district_no: "ML-09",
    district_code: "SWK",
    district_name: "South West Khasi Hills",
    state_no: "17",
  },
  {
    district_no: "ML-10",
    district_code: "WGH",
    district_name: "West Garo Hills",
    state_no: "17",
  },
  {
    district_no: "ML-11",
    district_code: "WJH",
    district_name: "West Jaintia Hills",
    state_no: "17",
  },
  {
    district_no: "ML-12",
    district_code: "WKH",
    district_name: "West Khasi Hills",
    state_no: "17",
  },
];

const districtsMZ = [
  {
    district_no: "MZ-01",
    district_code: "AIZ",
    district_name: "Aizawl",
    state_no: "15",
  },
  {
    district_no: "MZ-02",
    district_code: "CHA",
    district_name: "Champhai",
    state_no: "15",
  },
  {
    district_no: "MZ-03",
    district_code: "HNA",
    district_name: "Hnahthial",
    state_no: "15",
  },
  {
    district_no: "MZ-04",
    district_code: "KHA",
    district_name: "Khawzawl",
    state_no: "15",
  },
  {
    district_no: "MZ-05",
    district_code: "KOL",
    district_name: "Kolasib",
    state_no: "15",
  },
  {
    district_no: "MZ-06",
    district_code: "LAW",
    district_name: "Lawngtlai",
    state_no: "15",
  },
  {
    district_no: "MZ-07",
    district_code: "LUN",
    district_name: "Lunglei",
    state_no: "15",
  },
  {
    district_no: "MZ-08",
    district_code: "MAM",
    district_name: "Mamit",
    state_no: "15",
  },
  {
    district_no: "MZ-09",
    district_code: "SAI",
    district_name: "Siaha",
    state_no: "15",
  },
  {
    district_no: "MZ-10",
    district_code: "SAT",
    district_name: "Saitual",
    state_no: "15",
  },
  {
    district_no: "MZ-11",
    district_code: "SER",
    district_name: "Serchhip",
    state_no: "15",
  },
];

const districtsNL = [
  {
    district_no: "NL-01",
    district_code: "CMK",
    district_name: "Chümoukedima",
    state_no: "13",
  },
  {
    district_no: "NL-02",
    district_code: "DIM",
    district_name: "Dimapur",
    state_no: "13",
  },
  {
    district_no: "NL-03",
    district_code: "KIP",
    district_name: "Kiphire",
    state_no: "13",
  },
  {
    district_no: "NL-04",
    district_code: "KOH",
    district_name: "Kohima",
    state_no: "13",
  },
  {
    district_no: "NL-05",
    district_code: "LON",
    district_name: "Longleng",
    state_no: "13",
  },
  {
    district_no: "NL-06",
    district_code: "MOK",
    district_name: "Mokokchung",
    state_no: "13",
  },
  {
    district_no: "NL-07",
    district_code: "MON",
    district_name: "Mon",
    state_no: "13",
  },
  {
    district_no: "NL-08",
    district_code: "NIU",
    district_name: "Niuland",
    state_no: "13",
  },
  {
    district_no: "NL-09",
    district_code: "NOK",
    district_name: "Noklak",
    state_no: "13",
  },
  {
    district_no: "NL-10",
    district_code: "PER",
    district_name: "Peren",
    state_no: "13",
  },
  {
    district_no: "NL-11",
    district_code: "PHE",
    district_name: "Phek",
    state_no: "13",
  },
  {
    district_no: "NL-12",
    district_code: "SHA",
    district_name: "Shamator",
    state_no: "13",
  },
  {
    district_no: "NL-13",
    district_code: "TSE",
    district_name: "Tseminyu",
    state_no: "13",
  },
  {
    district_no: "NL-14",
    district_code: "TUE",
    district_name: "Tuensang",
    state_no: "13",
  },
  {
    district_no: "NL-15",
    district_code: "WOK",
    district_name: "Wokha",
    state_no: "13",
  },
  {
    district_no: "NL-16",
    district_code: "ZUN",
    district_name: "Zunheboto",
    state_no: "13",
  },
];

const districtsOR = [
  {
    district_no: "OR-01",
    district_code: "ANG",
    district_name: "Angul",
    state_no: "21",
  },
  {
    district_no: "OR-02",
    district_code: "BAL",
    district_name: "Balangir",
    state_no: "21",
  },
  {
    district_no: "OR-03",
    district_code: "BAS",
    district_name: "Balasore",
    state_no: "21",
  },
  {
    district_no: "OR-04",
    district_code: "BAR",
    district_name: "Bargarh",
    state_no: "21",
  },
  {
    district_no: "OR-05",
    district_code: "BHA",
    district_name: "Bhadrak",
    state_no: "21",
  },
  {
    district_no: "OR-06",
    district_code: "BOU",
    district_name: "Boudh",
    state_no: "21",
  },
  {
    district_no: "OR-07",
    district_code: "CUT",
    district_name: "Cuttack",
    state_no: "21",
  },
  {
    district_no: "OR-08",
    district_code: "DEO",
    district_name: "Deogarh",
    state_no: "21",
  },
  {
    district_no: "OR-09",
    district_code: "DHE",
    district_name: "Dhenkanal",
    state_no: "21",
  },
  {
    district_no: "OR-10",
    district_code: "GAJ",
    district_name: "Gajapati",
    state_no: "21",
  },
  {
    district_no: "OR-11",
    district_code: "GAN",
    district_name: "Ganjam",
    state_no: "21",
  },
  {
    district_no: "OR-12",
    district_code: "JAG",
    district_name: "Jagatsinghpur",
    state_no: "21",
  },
  {
    district_no: "OR-13",
    district_code: "JAJ",
    district_name: "Jajpur",
    state_no: "21",
  },
  {
    district_no: "OR-14",
    district_code: "JHA",
    district_name: "Jharsuguda",
    state_no: "21",
  },
  {
    district_no: "OR-15",
    district_code: "KAL",
    district_name: "Kalahandi",
    state_no: "21",
  },
  {
    district_no: "OR-16",
    district_code: "KAN",
    district_name: "Kandhamal",
    state_no: "21",
  },
  {
    district_no: "OR-17",
    district_code: "KEN",
    district_name: "Kendrapara",
    state_no: "21",
  },
  {
    district_no: "OR-18",
    district_code: "KEO",
    district_name: "Kendujhar (Keonjhar)",
    state_no: "21",
  },
  {
    district_no: "OR-19",
    district_code: "KHO",
    district_name: "Khordha",
    state_no: "21",
  },
  {
    district_no: "OR-20",
    district_code: "KOR",
    district_name: "Koraput",
    state_no: "21",
  },
  {
    district_no: "OR-21",
    district_code: "MAL",
    district_name: "Malkangiri",
    state_no: "21",
  },
  {
    district_no: "OR-22",
    district_code: "MAY",
    district_name: "Mayurbhanj",
    state_no: "21",
  },
  {
    district_no: "OR-23",
    district_code: "NAB",
    district_name: "Nabarangpur",
    state_no: "21",
  },
  {
    district_no: "OR-24",
    district_code: "NAY",
    district_name: "Nayagarh",
    state_no: "21",
  },
  {
    district_no: "OR-25",
    district_code: "NUA",
    district_name: "Nuapada",
    state_no: "21",
  },
  {
    district_no: "OR-26",
    district_code: "PUR",
    district_name: "Puri",
    state_no: "21",
  },
  {
    district_no: "OR-27",
    district_code: "RAY",
    district_name: "Rayagada",
    state_no: "21",
  },
  {
    district_no: "OR-28",
    district_code: "SAM",
    district_name: "Sambalpur",
    state_no: "21",
  },
  {
    district_no: "OR-29",
    district_code: "SUB",
    district_name: "Subarnapur (Sonepur)",
    state_no: "21",
  },
  {
    district_no: "OR-30",
    district_code: "SUN",
    district_name: "Sundargarh",
    state_no: "21",
  },
];

const districtsPB = [
  {
    district_no: "PB-01",
    district_code: "AMR",
    district_name: "Amritsar",
    state_no: "03",
  },
  {
    district_no: "PB-02",
    district_code: "BNL",
    district_name: "Barnala",
    state_no: "03",
  },
  {
    district_no: "PB-03",
    district_code: "BTI",
    district_name: "Bathinda",
    state_no: "03",
  },
  {
    district_no: "PB-04",
    district_code: "FDK",
    district_name: "Faridkot",
    state_no: "03",
  },
  {
    district_no: "PB-05",
    district_code: "FGS",
    district_name: "Fatehgarh Sahib",
    state_no: "03",
  },
  {
    district_no: "PB-06",
    district_code: "FAZ",
    district_name: "Fazilka",
    state_no: "03",
  },
  {
    district_no: "PB-07",
    district_code: "FZR",
    district_name: "Ferozepur",
    state_no: "03",
  },
  {
    district_no: "PB-08",
    district_code: "GUR",
    district_name: "Gurdaspur",
    state_no: "03",
  },
  {
    district_no: "PB-09",
    district_code: "HOS",
    district_name: "Hoshiarpur",
    state_no: "03",
  },
  {
    district_no: "PB-10",
    district_code: "JAL",
    district_name: "Jalandhar",
    state_no: "03",
  },
  {
    district_no: "PB-11",
    district_code: "KPT",
    district_name: "Kapurthala",
    state_no: "03",
  },
  {
    district_no: "PB-12",
    district_code: "LUD",
    district_name: "Ludhiana",
    state_no: "03",
  },
  {
    district_no: "PB-13",
    district_code: "MLK",
    district_name: "Malerkotla",
    state_no: "03",
  },
  {
    district_no: "PB-14",
    district_code: "MAN",
    district_name: "Mansa",
    state_no: "03",
  },
  {
    district_no: "PB-15",
    district_code: "MOG",
    district_name: "Moga",
    state_no: "03",
  },
  {
    district_no: "PB-16",
    district_code: "MUK",
    district_name: "Sri Muktsar Sahib",
    state_no: "03",
  },
  {
    district_no: "PB-17",
    district_code: "PTK",
    district_name: "Pathankot",
    state_no: "03",
  },
  {
    district_no: "PB-18",
    district_code: "PAT",
    district_name: "Patiala",
    state_no: "03",
  },
  {
    district_no: "PB-19",
    district_code: "RUP",
    district_name: "Rupnagar",
    state_no: "03",
  },
  {
    district_no: "PB-20",
    district_code: "SAS",
    district_name: "Sahibzada Ajit Singh Nagar",
    state_no: "03",
  },
  {
    district_no: "PB-21",
    district_code: "SAN",
    district_name: "Sangrur",
    state_no: "03",
  },
  {
    district_no: "PB-22",
    district_code: "SBS",
    district_name: "Shahid Bhagat Singh Nagar",
    state_no: "03",
  },
  {
    district_no: "PB-23",
    district_code: "TAR",
    district_name: "Tarn Taran",
    state_no: "03",
  },
];

const districtsRJ = [
  {
    district_no: "RJ-01",
    district_code: "AJM",
    district_name: "Ajmer",
    state_no: "08",
  },
  {
    district_no: "RJ-02",
    district_code: "ALW",
    district_name: "Alwar",
    state_no: "08",
  },
  {
    district_no: "RJ-03",
    district_code: "ANU",
    district_name: "Anupgarh",
    state_no: "08",
  },
  {
    district_no: "RJ-04",
    district_code: "BAL",
    district_name: "Balotra",
    state_no: "08",
  },
  {
    district_no: "RJ-05",
    district_code: "BNS",
    district_name: "Banswara",
    state_no: "08",
  },
  {
    district_no: "RJ-06",
    district_code: "BAR",
    district_name: "Baran",
    state_no: "08",
  },
  {
    district_no: "RJ-07",
    district_code: "BME",
    district_name: "Barmer",
    state_no: "08",
  },
  {
    district_no: "RJ-08",
    district_code: "BHA",
    district_name: "Bharatpur",
    state_no: "08",
  },
  {
    district_no: "RJ-09",
    district_code: "BHI",
    district_name: "Bhilwara",
    state_no: "08",
  },
  {
    district_no: "RJ-10",
    district_code: "BIK",
    district_name: "Bikaner",
    state_no: "08",
  },
  {
    district_no: "RJ-11",
    district_code: "BUN",
    district_name: "Bundi",
    state_no: "08",
  },
  {
    district_no: "RJ-12",
    district_code: "CHI",
    district_name: "Chittorgarh",
    state_no: "08",
  },
  {
    district_no: "RJ-13",
    district_code: "CHU",
    district_name: "Churu",
    state_no: "08",
  },
  {
    district_no: "RJ-14",
    district_code: "DAU",
    district_name: "Dausa",
    state_no: "08",
  },
  {
    district_no: "RJ-15",
    district_code: "DEE",
    district_name: "Deeg",
    state_no: "08",
  },
  {
    district_no: "RJ-16",
    district_code: "DHO",
    district_name: "Dholpur",
    state_no: "08",
  },
  {
    district_no: "RJ-17",
    district_code: "DID",
    district_name: "Didwana-Kuchaman",
    state_no: "08",
  },
  {
    district_no: "RJ-18",
    district_code: "DUD",
    district_name: "Dudu",
    state_no: "08",
  },
  {
    district_no: "RJ-19",
    district_code: "DUN",
    district_name: "Dungarpur",
    state_no: "08",
  },
  {
    district_no: "RJ-20",
    district_code: "GAC",
    district_name: "Gangapurcity",
    state_no: "08",
  },
  {
    district_no: "RJ-21",
    district_code: "GAN",
    district_name: "Ganganagar",
    state_no: "08",
  },
  {
    district_no: "RJ-22",
    district_code: "HAN",
    district_name: "Hanumangarh",
    state_no: "08",
  },
  {
    district_no: "RJ-23",
    district_code: "JAI",
    district_name: "Jaipur",
    state_no: "08",
  },
  {
    district_no: "RJ-24",
    district_code: "JAR",
    district_name: "Jaipur Rural",
    state_no: "08",
  },
  {
    district_no: "RJ-25",
    district_code: "JSM",
    district_name: "Jaisalmer",
    state_no: "08",
  },
  {
    district_no: "RJ-26",
    district_code: "JAL",
    district_name: "Jalore",
    state_no: "08",
  },
  {
    district_no: "RJ-27",
    district_code: "JHA",
    district_name: "Jhalawar",
    state_no: "08",
  },
  {
    district_no: "RJ-28",
    district_code: "JHU",
    district_name: "Jhunjhunu",
    state_no: "08",
  },
  {
    district_no: "RJ-29",
    district_code: "JOD",
    district_name: "Jodhpur",
    state_no: "08",
  },
  {
    district_no: "RJ-30",
    district_code: "JOR",
    district_name: "Jodhpur Rural",
    state_no: "08",
  },
  {
    district_no: "RJ-31",
    district_code: "KAR",
    district_name: "Karauli",
    state_no: "08",
  },
  {
    district_no: "RJ-32",
    district_code: "KEK",
    district_name: "Kekri",
    state_no: "08",
  },
  {
    district_no: "RJ-33",
    district_code: "KHA",
    district_name: "Khairthal-Tijara",
    state_no: "08",
  },
  {
    district_no: "RJ-34",
    district_code: "KOT",
    district_name: "Kota",
    state_no: "08",
  },
  {
    district_no: "RJ-35",
    district_code: "KOB",
    district_name: "Kotputli-Behror",
    state_no: "08",
  },
  {
    district_no: "RJ-36",
    district_code: "NAG",
    district_name: "Nagaur",
    state_no: "08",
  },
  {
    district_no: "RJ-37",
    district_code: "NKT",
    district_name: "Neem Ka Thana",
    state_no: "08",
  },
  {
    district_no: "RJ-38",
    district_code: "PAL",
    district_name: "Pali",
    state_no: "08",
  },
  {
    district_no: "RJ-39",
    district_code: "PHA",
    district_name: "Phalodi",
    state_no: "08",
  },
  {
    district_no: "RJ-40",
    district_code: "PRA",
    district_name: "Pratapgarh",
    state_no: "08",
  },
  {
    district_no: "RJ-41",
    district_code: "RAJ",
    district_name: "Rajsamand",
    state_no: "08",
  },
  {
    district_no: "RJ-42",
    district_code: "SAL",
    district_name: "Salumbar",
    state_no: "08",
  },
  {
    district_no: "RJ-43",
    district_code: "SAC",
    district_name: "Sanchore",
    state_no: "08",
  },
  {
    district_no: "RJ-44",
    district_code: "SAW",
    district_name: "Sawai Madhopur",
    state_no: "08",
  },
  {
    district_no: "RJ-45",
    district_code: "SHP",
    district_name: "Shahpura",
    state_no: "08",
  },
  {
    district_no: "RJ-46",
    district_code: "SIK",
    district_name: "Sikar",
    state_no: "08",
  },
  {
    district_no: "RJ-47",
    district_code: "SIR",
    district_name: "Sirohi",
    state_no: "08",
  },
  {
    district_no: "RJ-48",
    district_code: "TON",
    district_name: "Tonk",
    state_no: "08",
  },
  {
    district_no: "RJ-49",
    district_code: "UDA",
    district_name: "Udaipur",
    state_no: "08",
  },
];

const districtsSK = [
  {
    district_no: "SK-01",
    district_code: "GAN",
    district_name: "Gangtok",
    state_no: "11",
  },
  {
    district_no: "SK-02",
    district_code: "GYA",
    district_name: "Gyalshing",
    state_no: "11",
  },
  {
    district_no: "SK-03",
    district_code: "MAN",
    district_name: "Mangan",
    state_no: "11",
  },
  {
    district_no: "SK-04",
    district_code: "NAM",
    district_name: "Namchi",
    state_no: "11",
  },
  {
    district_no: "SK-05",
    district_code: "PAK",
    district_name: "Pakyong",
    state_no: "11",
  },
  {
    district_no: "SK-06",
    district_code: "SOR",
    district_name: "Soreng",
    state_no: "11",
  },
];

const districtsTN = [
  {
    district_no: "TN-01",
    district_code: "ARI",
    district_name: "Ariyalur",
    state_no: "33",
  },
  {
    district_no: "TN-02",
    district_code: "CGL",
    district_name: "Chengalpattu",
    state_no: "33",
  },
  {
    district_no: "TN-03",
    district_code: "CHE",
    district_name: "Chennai",
    state_no: "33",
  },
  {
    district_no: "TN-04",
    district_code: "COI",
    district_name: "Coimbatore",
    state_no: "33",
  },
  {
    district_no: "TN-05",
    district_code: "CUD",
    district_name: "Cuddalore",
    state_no: "33",
  },
  {
    district_no: "TN-06",
    district_code: "DHA",
    district_name: "Dharmapuri",
    state_no: "33",
  },
  {
    district_no: "TN-07",
    district_code: "DIN",
    district_name: "Dindigul",
    state_no: "33",
  },
  {
    district_no: "TN-08",
    district_code: "ERO",
    district_name: "Erode",
    state_no: "33",
  },
  {
    district_no: "TN-09",
    district_code: "KAL",
    district_name: "Kallakurichi",
    state_no: "33",
  },
  {
    district_no: "TN-10",
    district_code: "KNC",
    district_name: "Kanchipuram",
    state_no: "33",
  },
  {
    district_no: "TN-11",
    district_code: "KAN",
    district_name: "Kanyakumari",
    state_no: "33",
  },
  {
    district_no: "TN-12",
    district_code: "KAR",
    district_name: "Karur",
    state_no: "33",
  },
  {
    district_no: "TN-13",
    district_code: "KRI",
    district_name: "Krishnagiri",
    state_no: "33",
  },
  {
    district_no: "TN-14",
    district_code: "MAD",
    district_name: "Madurai",
    state_no: "33",
  },
  {
    district_no: "TN-15",
    district_code: "MAY",
    district_name: "Mayiladuthurai",
    state_no: "33",
  },
  {
    district_no: "TN-16",
    district_code: "NAG",
    district_name: "Nagapattinam",
    state_no: "33",
  },
  {
    district_no: "TN-17",
    district_code: "NAM",
    district_name: "Namakkal",
    state_no: "33",
  },
  {
    district_no: "TN-18",
    district_code: "NIL",
    district_name: "Nilgiris",
    state_no: "33",
  },
  {
    district_no: "TN-19",
    district_code: "PER",
    district_name: "Perambalur",
    state_no: "33",
  },
  {
    district_no: "TN-20",
    district_code: "PUD",
    district_name: "Pudukkottai",
    state_no: "33",
  },
  {
    district_no: "TN-21",
    district_code: "RAM",
    district_name: "Ramanathapuram",
    state_no: "33",
  },
  {
    district_no: "TN-22",
    district_code: "RAN",
    district_name: "Ranipet",
    state_no: "33",
  },
  {
    district_no: "TN-23",
    district_code: "SAL",
    district_name: "Salem",
    state_no: "33",
  },
  {
    district_no: "TN-24",
    district_code: "SIV",
    district_name: "Sivaganga",
    state_no: "33",
  },
  {
    district_no: "TN-25",
    district_code: "TEN",
    district_name: "Tenkasi",
    state_no: "33",
  },
  {
    district_no: "TN-26",
    district_code: "THA",
    district_name: "Thanjavur",
    state_no: "33",
  },
  {
    district_no: "TN-27",
    district_code: "THE",
    district_name: "Theni",
    state_no: "33",
  },
  {
    district_no: "TN-28",
    district_code: "THO",
    district_name: "Thoothukudi",
    state_no: "33",
  },
  {
    district_no: "TN-29",
    district_code: "TIR",
    district_name: "Tiruchirappalli",
    state_no: "33",
  },
  {
    district_no: "TN-30",
    district_code: "TIN",
    district_name: "Tirunelveli",
    state_no: "33",
  },
  {
    district_no: "TN-31",
    district_code: "TIP",
    district_name: "Tirupathur",
    state_no: "33",
  },
  {
    district_no: "TN-32",
    district_code: "TUP",
    district_name: "Tiruppur",
    state_no: "33",
  },
  {
    district_no: "TN-33",
    district_code: "TIV",
    district_name: "Tiruvallur",
    state_no: "33",
  },
  {
    district_no: "TN-34",
    district_code: "TVM",
    district_name: "Tiruvannamalai",
    state_no: "33",
  },
  {
    district_no: "TN-35",
    district_code: "TVR",
    district_name: "Tiruvarur",
    state_no: "33",
  },
  {
    district_no: "TN-36",
    district_code: "VEL",
    district_name: "Vellore",
    state_no: "33",
  },
  {
    district_no: "TN-37",
    district_code: "VIL",
    district_name: "Viluppuram",
    state_no: "33",
  },
  {
    district_no: "TN-38",
    district_code: "VIR",
    district_name: "Virudhunagar",
    state_no: "33",
  },
];

const districtsTS = [
  {
    district_no: "TS-01",
    district_code: "ADI",
    district_name: "Adilabad",
    state_no: "36",
  },
  {
    district_no: "TS-02",
    district_code: "BHA",
    district_name: "Bhadradri Kothagudem",
    state_no: "36",
  },
  {
    district_no: "TS-03",
    district_code: "HAN",
    district_name: "Hanamkonda",
    state_no: "36",
  },
  {
    district_no: "TS-04",
    district_code: "HYD",
    district_name: "Hyderabad",
    state_no: "36",
  },
  {
    district_no: "TS-05",
    district_code: "JAG",
    district_name: "Jagtial",
    state_no: "36",
  },
  {
    district_no: "TS-06",
    district_code: "JAN",
    district_name: "Jangaon",
    state_no: "36",
  },
  {
    district_no: "TS-07",
    district_code: "JAY",
    district_name: "Jayashankar Bhupalpally",
    state_no: "36",
  },
  {
    district_no: "TS-08",
    district_code: "JOG",
    district_name: "Jogulamba Gadwal",
    state_no: "36",
  },
  {
    district_no: "TS-09",
    district_code: "KAM",
    district_name: "Kamareddy",
    state_no: "36",
  },
  {
    district_no: "TS-10",
    district_code: "KAR",
    district_name: "Karimnagar",
    state_no: "36",
  },
  {
    district_no: "TS-11",
    district_code: "KHA",
    district_name: "Khammam",
    state_no: "36",
  },
  {
    district_no: "TS-12",
    district_code: "KOM",
    district_name: "Komaram Bheem Asifabad",
    state_no: "36",
  },
  {
    district_no: "TS-13",
    district_code: "MAB",
    district_name: "Mahabubabad",
    state_no: "36",
  },
  {
    district_no: "TS-14",
    district_code: "MAH",
    district_name: "Mahabubnagar",
    state_no: "36",
  },
  {
    district_no: "TS-15",
    district_code: "MAN",
    district_name: "Mancherial",
    state_no: "36",
  },
  {
    district_no: "TS-16",
    district_code: "MED",
    district_name: "Medak",
    state_no: "36",
  },
  {
    district_no: "TS-17",
    district_code: "MMG",
    district_name: "Medchal-Malkajgiri",
    state_no: "36",
  },
  {
    district_no: "TS-18",
    district_code: "MUL",
    district_name: "Mulugu",
    state_no: "36",
  },
  {
    district_no: "TS-19",
    district_code: "NAG",
    district_name: "Nagarkurnool",
    state_no: "36",
  },
  {
    district_no: "TS-20",
    district_code: "NAL",
    district_name: "Nalgonda",
    state_no: "36",
  },
  {
    district_no: "TS-21",
    district_code: "NAR",
    district_name: "Narayanpet",
    state_no: "36",
  },
  {
    district_no: "TS-22",
    district_code: "NIR",
    district_name: "Nirmal",
    state_no: "36",
  },
  {
    district_no: "TS-23",
    district_code: "NIZ",
    district_name: "Nizamabad",
    state_no: "36",
  },
  {
    district_no: "TS-24",
    district_code: "PED",
    district_name: "Peddapalli",
    state_no: "36",
  },
  {
    district_no: "TS-25",
    district_code: "RAJ",
    district_name: "Rajanna Sircilla",
    state_no: "36",
  },
  {
    district_no: "TS-26",
    district_code: "RAN",
    district_name: "Ranga Reddy",
    state_no: "36",
  },
  {
    district_no: "TS-27",
    district_code: "SAN",
    district_name: "Sangareddy",
    state_no: "36",
  },
  {
    district_no: "TS-28",
    district_code: "SID",
    district_name: "Siddipet",
    state_no: "36",
  },
  {
    district_no: "TS-29",
    district_code: "SUR",
    district_name: "Suryapet",
    state_no: "36",
  },
  {
    district_no: "TS-30",
    district_code: "VIK",
    district_name: "Vikarabad",
    state_no: "36",
  },
  {
    district_no: "TS-31",
    district_code: "WAN",
    district_name: "Wanaparthy",
    state_no: "36",
  },
  {
    district_no: "TS-32",
    district_code: "WAR",
    district_name: "Warangal",
    state_no: "36",
  },
  {
    district_no: "TS-33",
    district_code: "YAD",
    district_name: "Yadadri Bhuvanagiri",
    state_no: "36",
  },
];

const districtsTR = [
  {
    district_no: "TR-01",
    district_code: "DHA",
    district_name: "Dhalai",
    state_no: "16",
  },
  {
    district_no: "TR-02",
    district_code: "GOM",
    district_name: "Gomati",
    state_no: "16",
  },
  {
    district_no: "TR-03",
    district_code: "KHO",
    district_name: "Khowai",
    state_no: "16",
  },
  {
    district_no: "TR-04",
    district_code: "NTI",
    district_name: "North Tripura",
    state_no: "16",
  },
  {
    district_no: "TR-05",
    district_code: "SEP",
    district_name: "Sepahijala",
    state_no: "16",
  },
  {
    district_no: "TR-06",
    district_code: "STI",
    district_name: "South Tripura",
    state_no: "16",
  },
  {
    district_no: "TR-07",
    district_code: "UNA",
    district_name: "Unakoti",
    state_no: "16",
  },
  {
    district_no: "TR-08",
    district_code: "WTI",
    district_name: "West Tripura",
    state_no: "16",
  },
];

const districtsUK = [
  {
    district_no: "UK-01",
    district_code: "ALM",
    district_name: "Almora",
    state_no: "05",
  },
  {
    district_no: "UK-02",
    district_code: "BAG",
    district_name: "Bageshwar",
    state_no: "05",
  },
  {
    district_no: "UK-03",
    district_code: "CHA",
    district_name: "Chamoli",
    state_no: "05",
  },
  {
    district_no: "UK-04",
    district_code: "CHM",
    district_name: "Champawat",
    state_no: "05",
  },
  {
    district_no: "UK-05",
    district_code: "DEH",
    district_name: "Dehradun",
    state_no: "05",
  },
  {
    district_no: "UK-06",
    district_code: "HAR",
    district_name: "Haridwar",
    state_no: "05",
  },
  {
    district_no: "UK-07",
    district_code: "NAI",
    district_name: "Nainital",
    state_no: "05",
  },
  {
    district_no: "UK-08",
    district_code: "PAU",
    district_name: "Pauri Garhwal",
    state_no: "05",
  },
  {
    district_no: "UK-09",
    district_code: "PIT",
    district_name: "Pithoragarh",
    state_no: "05",
  },
  {
    district_no: "UK-10",
    district_code: "RUD",
    district_name: "Rudraprayag",
    state_no: "05",
  },
  {
    district_no: "UK-11",
    district_code: "TEH",
    district_name: "Tehri Garhwal",
    state_no: "05",
  },
  {
    district_no: "UK-12",
    district_code: "USN",
    district_name: "Udham Singh Nagar",
    state_no: "05",
  },
  {
    district_no: "UK-13",
    district_code: "UTT",
    district_name: "Uttarkashi",
    state_no: "05",
  },
];

const districtsUP = [
  {
    district_no: "UP-01",
    district_code: "AGR",
    district_name: "Agra",
    state_no: "09",
  },
  {
    district_no: "UP-02",
    district_code: "ALI",
    district_name: "Aligarh",
    state_no: "09",
  },
  {
    district_no: "UP-03",
    district_code: "AMB",
    district_name: "Ambedkar Nagar",
    state_no: "09",
  },
  {
    district_no: "UP-04",
    district_code: "AME",
    district_name: "Amethi",
    state_no: "09",
  },
  {
    district_no: "UP-05",
    district_code: "AMR",
    district_name: "Amroha",
    state_no: "09",
  },
  {
    district_no: "UP-06",
    district_code: "AUR",
    district_name: "Auraiya",
    state_no: "09",
  },
  {
    district_no: "UP-07",
    district_code: "AYO",
    district_name: "Ayodhya",
    state_no: "09",
  },
  {
    district_no: "UP-08",
    district_code: "AZA",
    district_name: "Azamgarh",
    state_no: "09",
  },
  {
    district_no: "UP-09",
    district_code: "BAG",
    district_name: "Baghpat",
    state_no: "09",
  },
  {
    district_no: "UP-10",
    district_code: "BAH",
    district_name: "Bahraich",
    state_no: "09",
  },
  {
    district_no: "UP-11",
    district_code: "BAL",
    district_name: "Ballia",
    state_no: "09",
  },
  {
    district_no: "UP-12",
    district_code: "BLR",
    district_name: "Balrampur",
    state_no: "09",
  },
  {
    district_no: "UP-13",
    district_code: "BAN",
    district_name: "Banda",
    state_no: "09",
  },
  {
    district_no: "UP-14",
    district_code: "BRB",
    district_name: "Barabanki",
    state_no: "09",
  },
  {
    district_no: "UP-15",
    district_code: "BAR",
    district_name: "Bareilly",
    state_no: "09",
  },
  {
    district_no: "UP-16",
    district_code: "BAS",
    district_name: "Basti",
    state_no: "09",
  },
  {
    district_no: "UP-17",
    district_code: "BHA",
    district_name: "Bhadohi",
    state_no: "09",
  },
  {
    district_no: "UP-18",
    district_code: "BIJ",
    district_name: "Bijnor",
    state_no: "09",
  },
  {
    district_no: "UP-19",
    district_code: "BUD",
    district_name: "Budaun",
    state_no: "09",
  },
  {
    district_no: "UP-20",
    district_code: "BUL",
    district_name: "Bulandshahr",
    state_no: "09",
  },
  {
    district_no: "UP-21",
    district_code: "CHA",
    district_name: "Chandauli",
    state_no: "09",
  },
  {
    district_no: "UP-22",
    district_code: "CHI",
    district_name: "Chitrakoot",
    state_no: "09",
  },
  {
    district_no: "UP-23",
    district_code: "DEO",
    district_name: "Deoria",
    state_no: "09",
  },
  {
    district_no: "UP-24",
    district_code: "ETA",
    district_name: "Etah",
    state_no: "09",
  },
  {
    district_no: "UP-25",
    district_code: "ETW",
    district_name: "Etawah",
    state_no: "09",
  },
  {
    district_no: "UP-26",
    district_code: "FAR",
    district_name: "Farrukhabad",
    state_no: "09",
  },
  {
    district_no: "UP-27",
    district_code: "FAT",
    district_name: "Fatehpur",
    state_no: "09",
  },
  {
    district_no: "UP-28",
    district_code: "FIR",
    district_name: "Firozabad",
    state_no: "09",
  },
  {
    district_no: "UP-29",
    district_code: "GBN",
    district_name: "Gautam Buddha Nagar",
    state_no: "09",
  },
  {
    district_no: "UP-30",
    district_code: "GHA",
    district_name: "Ghaziabad",
    state_no: "09",
  },
  {
    district_no: "UP-31",
    district_code: "GHZ",
    district_name: "Ghazipur",
    state_no: "09",
  },
  {
    district_no: "UP-32",
    district_code: "GON",
    district_name: "Gonda",
    state_no: "09",
  },
  {
    district_no: "UP-33",
    district_code: "GOR",
    district_name: "Gorakhpur",
    state_no: "09",
  },
  {
    district_no: "UP-34",
    district_code: "HAM",
    district_name: "Hamirpur",
    state_no: "09",
  },
  {
    district_no: "UP-35",
    district_code: "HAP",
    district_name: "Hapur",
    state_no: "09",
  },
  {
    district_no: "UP-36",
    district_code: "HAR",
    district_name: "Hardoi",
    state_no: "09",
  },
  {
    district_no: "UP-37",
    district_code: "HAT",
    district_name: "Hathras",
    state_no: "09",
  },
  {
    district_no: "UP-38",
    district_code: "JAL",
    district_name: "Jalaun",
    state_no: "09",
  },
  {
    district_no: "UP-39",
    district_code: "JAU",
    district_name: "Jaunpur",
    state_no: "09",
  },
  {
    district_no: "UP-40",
    district_code: "JHA",
    district_name: "Jhansi",
    state_no: "09",
  },
  {
    district_no: "UP-41",
    district_code: "KAN",
    district_name: "Kannauj",
    state_no: "09",
  },
  {
    district_no: "UP-42",
    district_code: "KAD",
    district_name: "Kanpur Dehat",
    state_no: "09",
  },
  {
    district_no: "UP-43",
    district_code: "KAN",
    district_name: "Kanpur Nagar",
    state_no: "09",
  },
  {
    district_no: "UP-44",
    district_code: "KAS",
    district_name: "Kasganj",
    state_no: "09",
  },
  {
    district_no: "UP-45",
    district_code: "KAU",
    district_name: "Kaushambi",
    state_no: "09",
  },
  {
    district_no: "UP-46",
    district_code: "KHE",
    district_name: "Kheri (Lakhimpur)",
    state_no: "09",
  },
  {
    district_no: "UP-47",
    district_code: "KUS",
    district_name: "Kushinagar",
    state_no: "09",
  },
  {
    district_no: "UP-48",
    district_code: "LAL",
    district_name: "Lalitpur",
    state_no: "09",
  },
  {
    district_no: "UP-49",
    district_code: "LUC",
    district_name: "Lucknow",
    state_no: "09",
  },
  {
    district_no: "UP-50",
    district_code: "MAH",
    district_name: "Maharajganj",
    state_no: "09",
  },
  {
    district_no: "UP-51",
    district_code: "MHB",
    district_name: "Mahoba",
    state_no: "09",
  },
  {
    district_no: "UP-52",
    district_code: "MAI",
    district_name: "Mainpuri",
    state_no: "09",
  },
  {
    district_no: "UP-53",
    district_code: "MAT",
    district_name: "Mathura",
    state_no: "09",
  },
  {
    district_no: "UP-54",
    district_code: "MAU",
    district_name: "Mau",
    state_no: "09",
  },
  {
    district_no: "UP-55",
    district_code: "MEE",
    district_name: "Meerut",
    state_no: "09",
  },
  {
    district_no: "UP-56",
    district_code: "MIR",
    district_name: "Mirzapur",
    state_no: "09",
  },
  {
    district_no: "UP-57",
    district_code: "MOR",
    district_name: "Moradabad",
    state_no: "09",
  },
  {
    district_no: "UP-58",
    district_code: "MUZ",
    district_name: "Muzaffarnagar",
    state_no: "09",
  },
  {
    district_no: "UP-59",
    district_code: "PIL",
    district_name: "Pilibhit",
    state_no: "09",
  },
  {
    district_no: "UP-60",
    district_code: "PRA",
    district_name: "Pratapgarh",
    state_no: "09",
  },
  {
    district_no: "UP-61",
    district_code: "PRY",
    district_name: "Prayagraj",
    state_no: "09",
  },
  {
    district_no: "UP-62",
    district_code: "RAE",
    district_name: "Raebareli",
    state_no: "09",
  },
  {
    district_no: "UP-63",
    district_code: "RAM",
    district_name: "Rampur",
    state_no: "09",
  },
  {
    district_no: "UP-64",
    district_code: "SAH",
    district_name: "Saharanpur",
    state_no: "09",
  },
  {
    district_no: "UP-65",
    district_code: "SAM",
    district_name: "Sambhal",
    state_no: "09",
  },
  {
    district_no: "UP-66",
    district_code: "SKN",
    district_name: "Sant Kabir Nagar",
    state_no: "09",
  },
  {
    district_no: "UP-67",
    district_code: "SHA",
    district_name: "Shahjahanpur",
    state_no: "09",
  },
  {
    district_no: "UP-68",
    district_code: "SHM",
    district_name: "Shamli",
    state_no: "09",
  },
  {
    district_no: "UP-69",
    district_code: "SHR",
    district_name: "Shravasti",
    state_no: "09",
  },
  {
    district_no: "UP-70",
    district_code: "SID",
    district_name: "Siddharthnagar",
    state_no: "09",
  },
  {
    district_no: "UP-71",
    district_code: "SIT",
    district_name: "Sitapur",
    state_no: "09",
  },
  {
    district_no: "UP-72",
    district_code: "SON",
    district_name: "Sonbhadra",
    state_no: "09",
  },
  {
    district_no: "UP-73",
    district_code: "SUL",
    district_name: "Sultanpur",
    state_no: "09",
  },
  {
    district_no: "UP-74",
    district_code: "UNN",
    district_name: "Unnao",
    state_no: "09",
  },
  {
    district_no: "UP-75",
    district_code: "VAR",
    district_name: "Varanasi",
    state_no: "09",
  },
];

const districtsWB = [
  {
    district_no: "WB-01",
    district_code: "ALI",
    district_name: "Alipurduar",
    state_no: "19",
  },
  {
    district_no: "WB-02",
    district_code: "BAN",
    district_name: "Bankura",
    state_no: "19",
  },
  {
    district_no: "WB-03",
    district_code: "BIR",
    district_name: "Birbhum",
    state_no: "19",
  },
  {
    district_no: "WB-04",
    district_code: "COO",
    district_name: "Cooch Behar",
    state_no: "19",
  },
  {
    district_no: "WB-05",
    district_code: "DDI",
    district_name: "Dakshin Dinajpur",
    state_no: "19",
  },
  {
    district_no: "WB-06",
    district_code: "DAR",
    district_name: "Darjeeling",
    state_no: "19",
  },
  {
    district_no: "WB-07",
    district_code: "HOO",
    district_name: "Hooghly",
    state_no: "19",
  },
  {
    district_no: "WB-08",
    district_code: "HOW",
    district_name: "Howrah",
    state_no: "19",
  },
  {
    district_no: "WB-09",
    district_code: "JAL",
    district_name: "Jalpaiguri",
    state_no: "19",
  },
  {
    district_no: "WB-10",
    district_code: "JHA",
    district_name: "Jhargram",
    state_no: "19",
  },
  {
    district_no: "WB-11",
    district_code: "KAL",
    district_name: "Kalimpong",
    state_no: "19",
  },
  {
    district_no: "WB-12",
    district_code: "KOL",
    district_name: "Kolkata",
    state_no: "19",
  },
  {
    district_no: "WB-13",
    district_code: "MAL",
    district_name: "Malda",
    state_no: "19",
  },
  {
    district_no: "WB-14",
    district_code: "MUR",
    district_name: "Murshidabad",
    state_no: "19",
  },
  {
    district_no: "WB-15",
    district_code: "NAD",
    district_name: "Nadia",
    state_no: "19",
  },
  {
    district_no: "WB-16",
    district_code: "N24",
    district_name: "North 24 Parganas",
    state_no: "19",
  },
  {
    district_no: "WB-17",
    district_code: "PBA",
    district_name: "Paschim Bardhaman",
    state_no: "19",
  },
  {
    district_no: "WB-18",
    district_code: "PME",
    district_name: "Paschim Medinipur",
    state_no: "19",
  },
  {
    district_no: "WB-19",
    district_code: "PBD",
    district_name: "Purba Bardhaman",
    state_no: "19",
  },
  {
    district_no: "WB-20",
    district_code: "PMD",
    district_name: "Purba Medinipur",
    state_no: "19",
  },
  {
    district_no: "WB-21",
    district_code: "PUR",
    district_name: "Purulia",
    state_no: "19",
  },
  {
    district_no: "WB-22",
    district_code: "S24",
    district_name: "South 24 Parganas",
    state_no: "19",
  },
  {
    district_no: "WB-23",
    district_code: "UDI",
    district_name: "Uttar Dinajpur",
    state_no: "19",
  },
];

// Union Territories
const districtsAN = [
  {
    district_no: "AN-01",
    district_code: "NIC",
    district_name: "Nicobar",
    state_no: "35",
  },
  {
    district_no: "AN-02",
    district_code: "NMA",
    district_name: "North and Middle Andaman",
    state_no: "35",
  },
  {
    district_no: "AN-03",
    district_code: "SAM",
    district_name: "South Andaman",
    state_no: "35",
  },
];

const districtsCH = [
  {
    district_no: "CH-01",
    district_code: "CHD",
    district_name: "Chandigarh",
    state_no: "04",
  },
];

const districtsDN = [
  {
    district_no: "DN-01",
    district_code: "DNH",
    district_name: "Dadra and Nagar Haveli",
    state_no: "26",
  },
  {
    district_no: "DN-02",
    district_code: "DAM",
    district_name: "Daman",
    state_no: "26",
  },
  {
    district_no: "DN-03",
    district_code: "DIU",
    district_name: "Diu",
    state_no: "26",
  },
];

const districtsDL = [
  {
    district_no: "DL-01",
    district_code: "CDE",
    district_name: "Central Delhi",
    state_no: "07",
  },
  {
    district_no: "DL-02",
    district_code: "EDE",
    district_name: "East Delhi",
    state_no: "07",
  },
  {
    district_no: "DL-03",
    district_code: "NDE",
    district_name: "New Delhi",
    state_no: "07",
  },
  {
    district_no: "DL-04",
    district_code: "NOD",
    district_name: "North Delhi",
    state_no: "07",
  },
  {
    district_no: "DL-05",
    district_code: "NED",
    district_name: "North East Delhi",
    state_no: "07",
  },
  {
    district_no: "DL-06",
    district_code: "NWD",
    district_name: "North West Delhi",
    state_no: "07",
  },
  {
    district_no: "DL-07",
    district_code: "SHA",
    district_name: "Shahdara",
    state_no: "07",
  },
  {
    district_no: "DL-08",
    district_code: "SDE",
    district_name: "South Delhi",
    state_no: "07",
  },
  {
    district_no: "DL-09",
    district_code: "SED",
    district_name: "South East Delhi",
    state_no: "07",
  },
  {
    district_no: "DL-10",
    district_code: "SWD",
    district_name: "South West Delhi",
    state_no: "07",
  },
  {
    district_no: "DL-11",
    district_code: "WDE",
    district_name: "West Delhi",
    state_no: "07",
  },
];

const districtsJK = [
  {
    district_no: "JK-01",
    district_code: "ANA",
    district_name: "Anantnag",
    state_no: "01",
  },
  {
    district_no: "JK-02",
    district_code: "BPR",
    district_name: "Bandipora",
    state_no: "01",
  },
  {
    district_no: "JK-03",
    district_code: "BAM",
    district_name: "Baramulla",
    state_no: "01",
  },
  {
    district_no: "JK-04",
    district_code: "BUD",
    district_name: "Budgam",
    state_no: "01",
  },
  {
    district_no: "JK-05",
    district_code: "DOD",
    district_name: "Doda",
    state_no: "01",
  },
  {
    district_no: "JK-06",
    district_code: "GAN",
    district_name: "Ganderbal",
    state_no: "01",
  },
  {
    district_no: "JK-07",
    district_code: "JAM",
    district_name: "Jammu",
    state_no: "01",
  },
  {
    district_no: "JK-08",
    district_code: "KAT",
    district_name: "Kathua",
    state_no: "01",
  },
  {
    district_no: "JK-09",
    district_code: "KIS",
    district_name: "Kishtwar",
    state_no: "01",
  },
  {
    district_no: "JK-10",
    district_code: "KUL",
    district_name: "Kulgam",
    state_no: "01",
  },
  {
    district_no: "JK-11",
    district_code: "KUP",
    district_name: "Kupwara",
    state_no: "01",
  },
  {
    district_no: "JK-12",
    district_code: "POO",
    district_name: "Poonch",
    state_no: "01",
  },
  {
    district_no: "JK-13",
    district_code: "PUL",
    district_name: "Pulwama",
    state_no: "01",
  },
  {
    district_no: "JK-14",
    district_code: "RAJ",
    district_name: "Rajouri",
    state_no: "01",
  },
  {
    district_no: "JK-15",
    district_code: "RAM",
    district_name: "Ramban",
    state_no: "01",
  },
  {
    district_no: "JK-16",
    district_code: "REA",
    district_name: "Reasi",
    state_no: "01",
  },
  {
    district_no: "JK-17",
    district_code: "SAM",
    district_name: "Samba",
    state_no: "01",
  },
  {
    district_no: "JK-18",
    district_code: "SHO",
    district_name: "Shopian",
    state_no: "01",
  },
  {
    district_no: "JK-19",
    district_code: "SRI",
    district_name: "Srinagar",
    state_no: "01",
  },
  {
    district_no: "JK-20",
    district_code: "UDH",
    district_name: "Udhampur",
    state_no: "01",
  },
];

const districtsLA = [
  {
    district_no: "LA-01",
    district_code: "KGL",
    district_name: "Kargil",
    state_no: "38",
  },
  {
    district_no: "LA-02",
    district_code: "LEH",
    district_name: "Leh",
    state_no: "38",
  },
];

const districtsLD = [
  {
    district_no: "LD-01",
    district_code: "LAK",
    district_name: "Lakshadweep",
    state_no: "31",
  },
];

const districtsPY = [
  {
    district_no: "PY-01",
    district_code: "KAR",
    district_name: "Karaikal",
    state_no: "34",
  },
  {
    district_no: "PY-02",
    district_code: "MAH",
    district_name: "Mahe",
    state_no: "34",
  },
  {
    district_no: "PY-03",
    district_code: "PUD",
    district_name: "Puducherry",
    state_no: "34",
  },
  {
    district_no: "PY-04",
    district_code: "YAN",
    district_name: "Yanam",
    state_no: "34",
  },
];

export const districts = [
  ...districtsAP,
  ...districtsAR,
  ...districtsAS,
  ...districtsBR,
  ...districtsCG,
  ...districtsGA,
  ...districtsGJ,
  ...districtsHR,
  ...districtsHP,
  ...districtsJH,
  ...districtsKA,
  ...districtsKL,
  ...districtsMP,
  ...districtsMH,
  ...districtsMN,
  ...districtsML,
  ...districtsMZ,
  ...districtsNL,
  ...districtsOR,
  ...districtsPB,
  ...districtsRJ,
  ...districtsSK,
  ...districtsTN,
  ...districtsTS,
  ...districtsTR,
  ...districtsUK,
  ...districtsUP,
  ...districtsWB,
  ...districtsAN,
  ...districtsCH,
  ...districtsDN,
  ...districtsDL,
  ...districtsJK,
  ...districtsLA,
  ...districtsLD,
  ...districtsPY,
];
