import { FeeRuleSeed } from "../types";

const feeRules_MH: FeeRuleSeed[] = [
  {
    state_code: "MH",
    category_code: "BULLION_WEIGHTS",
    min_value: 0.001,
    max_value: 500,
    unit: "g",
    fee_amount: 30,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "BULLION_WEIGHTS",
    min_value: 1000,
    max_value: 5000,
    unit: "g",
    fee_amount: 40,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "BULLION_WEIGHTS",
    min_value: 10000,
    max_value: 10000,
    unit: "g",
    fee_amount: 60,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "CARAT_WEIGHTS",
    min_value: 0.001,
    max_value: 100,
    unit: "g",
    fee_amount: 40,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "SHEET_METAL_WEIGHTS",
    min_value: 0.001,
    max_value: 0.5,
    unit: "g",
    fee_amount: 10,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "CYLINDRICAL_KNOB_WEIGHTS",
    min_value: 1,
    max_value: 500,
    unit: "g",
    fee_amount: 10,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "CYLINDRICAL_KNOB_WEIGHTS",
    min_value: 1000,
    max_value: 1000,
    unit: "g",
    fee_amount: 20,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "CYLINDRICAL_KNOB_WEIGHTS",
    min_value: 2000,
    max_value: 2000,
    unit: "g",
    fee_amount: 30,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "CYLINDRICAL_KNOB_WEIGHTS",
    min_value: 5000,
    max_value: 20000,
    unit: "g",
    fee_amount: 40,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "CYLINDRICAL_KNOB_WEIGHTS",
    min_value: 50000,
    max_value: 50000,
    unit: "g",
    fee_amount: 50,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "IRON_HEXAGONAL_KNOB_PARALLELEPIPED_WEIGHTS",
    min_value: 1,
    max_value: 500,
    unit: "kg",
    fee_amount: 10,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "IRON_HEXAGONAL_KNOB_PARALLELEPIPED_WEIGHTS",
    min_value: 1000,
    max_value: 1000,
    unit: "kg",
    fee_amount: 20,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "IRON_HEXAGONAL_KNOB_PARALLELEPIPED_WEIGHTS",
    min_value: 2000,
    max_value: 2000,
    unit: "kg",
    fee_amount: 30,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "IRON_HEXAGONAL_KNOB_PARALLELEPIPED_WEIGHTS",
    min_value: 5000,
    max_value: 20000,
    unit: "kg",
    fee_amount: 40,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "IRON_HEXAGONAL_KNOB_PARALLELEPIPED_WEIGHTS",
    min_value: 50000,
    max_value: 50000,
    unit: "kg",
    fee_amount: 50,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 100,
    max_value: 100,
    unit: "kg",
    fee_amount: 150,
    fee_basis: "PER_PIECE",
    condition: "MPE 0.05/10000",
  },

  {
    state_code: "MH",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 100,
    max_value: 100,
    unit: "kg",
    fee_amount: 100,
    fee_basis: "PER_PIECE",
    condition: "MPE 3.3/10000, 1.7/10000 and 1.0/10000",
  },

  {
    state_code: "MH",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 200,
    max_value: 200,
    unit: "kg",
    fee_amount: 300,
    fee_basis: "PER_PIECE",
    condition: "MPE 0.05/10000",
  },

  {
    state_code: "MH",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 200,
    max_value: 200,
    unit: "kg",
    fee_amount: 200,
    fee_basis: "PER_PIECE",
    condition: "MPE 3.3/10000, 1.7/10000 and 1.0/10000",
  },

  {
    state_code: "MH",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 500,
    max_value: 500,
    unit: "kg",
    fee_amount: 600,
    fee_basis: "PER_PIECE",
    condition: "MPE 0.05/10000",
  },

  {
    state_code: "MH",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 500,
    max_value: 500,
    unit: "kg",
    fee_amount: 400,
    fee_basis: "PER_PIECE",
    condition: "MPE 3.3/10000, 1.7/10000 and 1.0/10000",
  },

  {
    state_code: "MH",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 1000,
    max_value: 1000,
    unit: "kg",
    fee_amount: 1500,
    fee_basis: "PER_PIECE",
    condition: "MPE 0.05/10000",
  },

  {
    state_code: "MH",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 1000,
    max_value: 1000,
    unit: "kg",
    fee_amount: 1000,
    fee_basis: "PER_PIECE",
    condition: "MPE 3.3/10000, 1.7/10000 and 1.0/10000",
  },

  {
    state_code: "MH",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 2000,
    max_value: 2000,
    unit: "kg",
    fee_amount: 3000,
    fee_basis: "PER_PIECE",
    condition: "MPE 0.05/10000",
  },

  {
    state_code: "MH",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 2000,
    max_value: 2000,
    unit: "kg",
    fee_amount: 2000,
    fee_basis: "PER_PIECE",
    condition: "MPE 3.3/10000, 1.7/10000 and 1.0/10000",
  },

  {
    state_code: "MH",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 5000,
    max_value: 5000,
    unit: "kg",
    fee_amount: 5000,
    fee_basis: "PER_PIECE",
    condition: "MPE 0.05/10000",
  },

  {
    state_code: "MH",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 5000,
    max_value: 5000,
    unit: "kg",
    fee_amount: 4000,
    fee_basis: "PER_PIECE",
    condition: "MPE 3.3/10000, 1.7/10000 and 1.0/10000",
  },
  {
    state_code: "MH",
    category_code: "CAPACITY_MEASURES",
    min_value: 0.001,
    max_value: 5,
    unit: "litre",
    fee_amount: 20,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "CAPACITY_MEASURES",
    min_value: 10,
    max_value: 20,
    unit: "litre",
    fee_amount: 40,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "CAPACITY_MEASURES",
    min_value: 50,
    max_value: 50,
    unit: "litre",
    fee_amount: 100,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "CAPACITY_MEASURES",
    min_value: 100,
    max_value: null,
    unit: "litre",
    fee_amount: 100,
    fee_basis: "PER_PIECE",
    condition: "₹100 for first 100 litre",
    additional_fee: 14,
    additional_unit: 100,
    maximum_fee: 5000,
  },
  {
    state_code: "MH",
    category_code: "NON_FLEXIBLE_LENGTH_MEASURES",
    min_value: 0.5,
    max_value: 1,
    unit: "metre",
    fee_amount: 40,
    fee_basis: "PER_PIECE",
    condition: "Graduated at every centimetre",
  },

  {
    state_code: "MH",
    category_code: "NON_FLEXIBLE_LENGTH_MEASURES",
    min_value: 0.5,
    max_value: 2,
    unit: "metre",
    fee_amount: 20,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "FABRIC_PLASTIC_WOVEN_STEEL_TAPES",
    min_value: null,
    max_value: null,
    unit: "metre",
    fee_amount: 2,
    fee_basis: "PER_METRE",
    condition: "Class-I",
  },

  {
    state_code: "MH",
    category_code: "FABRIC_PLASTIC_WOVEN_STEEL_TAPES",
    min_value: null,
    max_value: null,
    unit: "metre",
    fee_amount: 1,
    fee_basis: "PER_METRE",
    condition: "Class-II and Class-III",
  },
  {
    state_code: "MH",
    category_code: "FOLDING_SCALES",
    min_value: 0.5,
    max_value: 1,
    unit: "metre",
    fee_amount: 20,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "SURVEYING_CHAIN",
    min_value: 20,
    max_value: 30,
    unit: "metre",
    fee_amount: 200,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "BEAM_SCALES_CLASS_A_B",
    min_value: 0,
    max_value: 500,
    unit: "g",
    fee_amount: 120,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "BEAM_SCALES_CLASS_A_B",
    min_value: 1,
    max_value: 5,
    unit: "kg",
    fee_amount: 200,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "BEAM_SCALES_CLASS_A_B",
    min_value: 10,
    max_value: 50,
    unit: "kg",
    fee_amount: 300,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "BEAM_SCALES_CLASS_A_B",
    min_value: 100,
    max_value: 100,
    unit: "kg",
    fee_amount: 600,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "BEAM_SCALES_CLASS_A_B",
    min_value: 200,
    max_value: 200,
    unit: "kg",
    fee_amount: 800,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "BEAM_SCALES_CLASS_C_D",
    min_value: 0,
    max_value: 500,
    unit: "g",
    fee_amount: 20,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "BEAM_SCALES_CLASS_C_D",
    min_value: 1,
    max_value: 5,
    unit: "kg",
    fee_amount: 30,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "BEAM_SCALES_CLASS_C_D",
    min_value: 10,
    max_value: 50,
    unit: "kg",
    fee_amount: 40,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "BEAM_SCALES_CLASS_C_D",
    min_value: 100,
    max_value: 200,
    unit: "kg",
    fee_amount: 200,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "BEAM_SCALES_CLASS_C_D",
    min_value: 300,
    max_value: 1000,
    unit: "kg",
    fee_amount: 400,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 0,
    max_value: 1,
    unit: "kg",
    fee_amount: 30,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 2,
    max_value: 15,
    unit: "kg",
    fee_amount: 60,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 16,
    max_value: 25,
    unit: "kg",
    fee_amount: 120,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 26,
    max_value: 200,
    unit: "kg",
    fee_amount: 200,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 201,
    max_value: 300,
    unit: "kg",
    fee_amount: 400,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 301,
    max_value: 1500,
    unit: "kg",
    fee_amount: 600,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 1501,
    max_value: 3000,
    unit: "kg",
    fee_amount: 800,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 3001,
    max_value: 5000,
    unit: "kg",
    fee_amount: 1000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 5001,
    max_value: 10000,
    unit: "kg",
    fee_amount: 2000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 10001,
    max_value: 150000,
    unit: "kg",
    fee_amount: 4000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 150001,
    max_value: null,
    unit: "kg",
    fee_amount: 5000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_ELECTRONIC_CLASS_III_IV",
    min_value: 20,
    max_value: 300,
    unit: "kg",
    fee_amount: 400,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_ELECTRONIC_CLASS_III_IV",
    min_value: 301,
    max_value: 1500,
    unit: "kg",
    fee_amount: 600,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_ELECTRONIC_CLASS_III_IV",
    min_value: 1501,
    max_value: 3000,
    unit: "kg",
    fee_amount: 1000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_ELECTRONIC_CLASS_III_IV",
    min_value: 3001,
    max_value: 10000,
    unit: "kg",
    fee_amount: 2000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_ELECTRONIC_CLASS_III_IV",
    min_value: 10001,
    max_value: 150000,
    unit: "kg",
    fee_amount: 4000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_ELECTRONIC_CLASS_III_IV",
    min_value: 150001,
    max_value: null,
    unit: "kg",
    fee_amount: 5000,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_CLASS_I_II",
    min_value: 0,
    max_value: 10,
    unit: "kg",
    fee_amount: 400,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_CLASS_I_II",
    min_value: 11,
    max_value: 50,
    unit: "kg",
    fee_amount: 500,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_CLASS_I_II",
    min_value: 51,
    max_value: 1000,
    unit: "kg",
    fee_amount: 1000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_CLASS_I_II",
    min_value: 1001,
    max_value: 10000,
    unit: "kg",
    fee_amount: 2000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_CLASS_I_II",
    min_value: 10001,
    max_value: 50000,
    unit: "kg",
    fee_amount: 4000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "NON_AUTOMATIC_WEIGHING_CLASS_I_II",
    min_value: 50001,
    max_value: null,
    unit: "kg",
    fee_amount: 5000,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "AUTOMATIC_WEIGHING_INSTRUMENTS",
    min_value: 0,
    max_value: 10,
    unit: "kg",
    fee_amount: 400,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "AUTOMATIC_WEIGHING_INSTRUMENTS",
    min_value: 11,
    max_value: 50,
    unit: "kg",
    fee_amount: 500,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "AUTOMATIC_WEIGHING_INSTRUMENTS",
    min_value: 51,
    max_value: 1000,
    unit: "kg",
    fee_amount: 1000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "AUTOMATIC_WEIGHING_INSTRUMENTS",
    min_value: 1001,
    max_value: 10000,
    unit: "kg",
    fee_amount: 2000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "AUTOMATIC_WEIGHING_INSTRUMENTS",
    min_value: 10001,
    max_value: 50000,
    unit: "kg",
    fee_amount: 4000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "MH",
    category_code: "AUTOMATIC_WEIGHING_INSTRUMENTS",
    min_value: 50001,
    max_value: null,
    unit: "kg",
    fee_amount: 5000,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "MH",
    category_code: "DISPENSING_PUMPS",
    min_value: null,
    max_value: null,
    unit: "unit",
    fee_amount: 2000,
    fee_basis: "FIXED",
  },
  {
    state_code: "MH",
    category_code: "VOLUMETRIC_TOTALIZING_COUNTER",
    min_value: null,
    max_value: null,
    unit: "unit",
    fee_amount: 1000,
    fee_basis: "FIXED",
  },
  {
    state_code: "MH",
    category_code: "VOLUMETRIC_OTHER_INSTRUMENTS",
    min_value: 0,
    max_value: 20,
    unit: "litre",
    fee_amount: 400,
    fee_basis: "FIXED",
  },

  {
    state_code: "MH",
    category_code: "VOLUMETRIC_OTHER_INSTRUMENTS",
    min_value: 21,
    max_value: 50,
    unit: "litre",
    fee_amount: 500,
    fee_basis: "FIXED",
  },

  {
    state_code: "MH",
    category_code: "VOLUMETRIC_OTHER_INSTRUMENTS",
    min_value: 51,
    max_value: 100,
    unit: "litre",
    fee_amount: 1000,
    fee_basis: "FIXED",
  },

  {
    state_code: "MH",
    category_code: "VOLUMETRIC_OTHER_INSTRUMENTS",
    min_value: 101,
    max_value: null,
    unit: "litre",
    fee_amount: 1000,
    fee_basis: "FIXED",
    condition:
      "₹1000 for first 100 litres plus ₹500 for every additional 100 litres or part thereof",
    additional_fee: 500,
    additional_unit: 100,
    maximum_fee: 5000,
  },
  {
    state_code: "MH",
    category_code: "BULK_METERS_LIQUID_OTHER_THAN_WATER",
    min_value: 0,
    max_value: 100,
    unit: "litre/min",
    fee_amount: 4000,
    fee_basis: "FIXED",
  },

  {
    state_code: "MH",
    category_code: "BULK_METERS_LIQUID_OTHER_THAN_WATER",
    min_value: 101,
    max_value: null,
    unit: "litre/min",
    fee_amount: 5000,
    fee_basis: "FIXED",
  },
  {
    state_code: "MH",
    category_code: "BULK_METER_TOTALIZING_COUNTER",
    min_value: null,
    max_value: null,
    unit: "unit",
    fee_amount: 1000,
    fee_basis: "FIXED",
  },
  {
    state_code: "MH",
    category_code: "TAXI_AUTO_RICKSHAW_METERS",
    min_value: null,
    max_value: null,
    unit: "unit",
    fee_amount: 200,
    fee_basis: "FIXED",
  },
  {
    state_code: "MH",
    category_code: "OTHER_LINEAR_METERS",
    min_value: 0,
    max_value: 1000,
    unit: "metre",
    fee_amount: 100,
    fee_basis: "FIXED",
    condition: "₹100 for the first 1000 metres or part thereof",
    additional_fee: 10,
    additional_unit: 100,
    maximum_fee: 5000,
  },
  {
    state_code: "MH",
    category_code: "CLINICAL_THERMOMETER",
    min_value: null,
    max_value: null,
    unit: "unit",
    fee_amount: 1,
    fee_basis: "FIXED",
  },
  {
    state_code: "MH",
    category_code: "WATER_METER",
    min_value: null,
    max_value: null,
    unit: "unit",
    fee_amount: 50,
    fee_basis: "FIXED",
  },
  {
    state_code: "MH",
    category_code: "PEG_MEASURE",
    min_value: 30,
    max_value: 100,
    unit: "ml",
    fee_amount: 100,
    fee_basis: "PER_PIECE",
    condition: "Applicable to 30 ml, 60 ml and 100 ml",
  },
  {
    state_code: "MH",
    category_code: "CNG_DISPENSERS",
    min_value: null,
    max_value: null,
    unit: "unit",
    fee_amount: 2000,
    fee_basis: "FIXED",
  },
  {
    state_code: "MH",
    category_code: "CNG_TOTALIZING_COUNTERS",
    min_value: null,
    max_value: null,
    unit: "unit",
    fee_amount: 1000,
    fee_basis: "FIXED",
  },
  {
    state_code: "MH",
    category_code: "LPG_DISPENSERS",
    min_value: null,
    max_value: null,
    unit: "unit",
    fee_amount: 2000,
    fee_basis: "FIXED",
  },
  {
    state_code: "MH",
    category_code: "LPG_TOTALIZING_COUNTERS",
    min_value: null,
    max_value: null,
    unit: "unit",
    fee_amount: 1000,
    fee_basis: "FIXED",
  },
];

const feeRules_UP: FeeRuleSeed[] = [
  {
    state_code: "UP",
    category_code: "BULLION_WEIGHTS",
    min_value: 10000,
    max_value: 10000,
    unit: "g",
    fee_amount: 30,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "BULLION_WEIGHTS",
    min_value: 5000,
    max_value: 5000,
    unit: "g",
    fee_amount: 20,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "BULLION_WEIGHTS",
    min_value: 1000,
    max_value: 2000,
    unit: "g",
    fee_amount: 20,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "BULLION_WEIGHTS",
    min_value: 1,
    max_value: 500,
    unit: "g",
    fee_amount: 15,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "CARAT_WEIGHTS",
    min_value: 0.001,
    max_value: 100,
    unit: "g",
    fee_amount: 20,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "CYLINDRICAL_KNOB_WEIGHTS",
    min_value: 1000,
    max_value: 10000,
    unit: "g",
    fee_amount: 20,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "CYLINDRICAL_KNOB_WEIGHTS",
    min_value: 1,
    max_value: 500,
    unit: "g",
    fee_amount: 5,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "SHEET_METAL_WEIGHTS",
    min_value: 0.001,
    max_value: 0.5,
    unit: "g",
    fee_amount: 5,
    fee_basis: "PER_PIECE",
  },
  {
    state_code: "UP",
    category_code: "IRON_HEXAGONAL_KNOB_PARALLELEPIPED_WEIGHTS",
    min_value: 50000,
    max_value: 50000,
    unit: "g",
    fee_amount: 25,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "IRON_HEXAGONAL_KNOB_PARALLELEPIPED_WEIGHTS",
    min_value: 5000,
    max_value: 20000,
    unit: "g",
    fee_amount: 20,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "IRON_HEXAGONAL_KNOB_PARALLELEPIPED_WEIGHTS",
    min_value: 2000,
    max_value: 2000,
    unit: "g",
    fee_amount: 15,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "IRON_HEXAGONAL_KNOB_PARALLELEPIPED_WEIGHTS",
    min_value: 1000,
    max_value: 1000,
    unit: "g",
    fee_amount: 10,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "IRON_HEXAGONAL_KNOB_PARALLELEPIPED_WEIGHTS",
    min_value: 1,
    max_value: 500,
    unit: "g",
    fee_amount: 5,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 100,
    max_value: 100,
    unit: "kg",
    fee_amount: 75,
    fee_basis: "PER_PIECE",
    condition: "MPE 0.5/10000",
  },

  {
    state_code: "UP",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 200,
    max_value: 200,
    unit: "kg",
    fee_amount: 150,
    fee_basis: "PER_PIECE",
    condition: "MPE 0.5/10000",
  },

  {
    state_code: "UP",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 500,
    max_value: 500,
    unit: "kg",
    fee_amount: 300,
    fee_basis: "PER_PIECE",
    condition: "MPE 0.5/10000",
  },

  {
    state_code: "UP",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 1000,
    max_value: 1000,
    unit: "kg",
    fee_amount: 750,
    fee_basis: "PER_PIECE",
    condition: "MPE 0.5/10000",
  },

  {
    state_code: "UP",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 2000,
    max_value: 2000,
    unit: "kg",
    fee_amount: 1500,
    fee_basis: "PER_PIECE",
    condition: "MPE 0.5/10000",
  },

  {
    state_code: "UP",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 5000,
    max_value: 5000,
    unit: "kg",
    fee_amount: 3000,
    fee_basis: "PER_PIECE",
    condition: "MPE 0.5/10000",
  },

  {
    state_code: "UP",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 100,
    max_value: 100,
    unit: "kg",
    fee_amount: 50,
    fee_basis: "PER_PIECE",
    condition: "MPE 3.3/10000, 1.7/10000 and 1.0/10000",
  },

  {
    state_code: "UP",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 200,
    max_value: 200,
    unit: "kg",
    fee_amount: 100,
    fee_basis: "PER_PIECE",
    condition: "MPE 3.3/10000, 1.7/10000 and 1.0/10000",
  },

  {
    state_code: "UP",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 500,
    max_value: 500,
    unit: "kg",
    fee_amount: 200,
    fee_basis: "PER_PIECE",
    condition: "MPE 3.3/10000, 1.7/10000 and 1.0/10000",
  },

  {
    state_code: "UP",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 1000,
    max_value: 1000,
    unit: "kg",
    fee_amount: 500,
    fee_basis: "PER_PIECE",
    condition: "MPE 3.3/10000, 1.7/10000 and 1.0/10000",
  },

  {
    state_code: "UP",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 2000,
    max_value: 2000,
    unit: "kg",
    fee_amount: 1000,
    fee_basis: "PER_PIECE",
    condition: "MPE 3.3/10000, 1.7/10000 and 1.0/10000",
  },

  {
    state_code: "UP",
    category_code: "HIGH_CAPACITY_WEIGHING_STANDARD_WEIGHTS",
    min_value: 5000,
    max_value: 5000,
    unit: "kg",
    fee_amount: 2000,
    fee_basis: "PER_PIECE",
    condition: "MPE 3.3/10000, 1.7/10000 and 1.0/10000",
  },

  {
    state_code: "UP",
    category_code: "CAPACITY_MEASURES",
    min_value: 0.001,
    max_value: 5,
    unit: "litre",
    fee_amount: 10,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "CAPACITY_MEASURES",
    min_value: 10,
    max_value: 20,
    unit: "litre",
    fee_amount: 20,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "CAPACITY_MEASURES",
    min_value: 50,
    max_value: 50,
    unit: "litre",
    fee_amount: 50,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "CAPACITY_MEASURES",
    min_value: 100,
    max_value: null,
    unit: "litre",
    fee_amount: 50,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_FLEXIBLE_LENGTH_MEASURES",
    min_value: 0.5,
    max_value: 0.5,
    unit: "metre",
    fee_amount: 20,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_FLEXIBLE_LENGTH_MEASURES",
    min_value: 0.501,
    max_value: 1,
    unit: "metre",
    fee_amount: 20,
    fee_basis: "PER_PIECE",
    condition: "Graduated at every centimetre",
  },

  {
    state_code: "UP",
    category_code: "NON_FLEXIBLE_LENGTH_MEASURES",
    min_value: 1.001,
    max_value: 2,
    unit: "metre",
    fee_amount: 10,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "FABRIC_PLASTIC_WOVEN_STEEL_TAPES",
    min_value: 0,
    max_value: null,
    unit: "metre",
    fee_amount: 1,
    fee_basis: "PER_METRE",
    condition: "Class-I and Class-II",
  },

  {
    state_code: "UP",
    category_code: "FABRIC_PLASTIC_WOVEN_STEEL_TAPES",
    min_value: 0,
    max_value: null,
    unit: "metre",
    fee_amount: 0.5,
    fee_basis: "PER_METRE",
    condition: "Class-III",
  },

  {
    state_code: "UP",
    category_code: "FOLDING_SCALES",
    min_value: 0.5,
    max_value: 1,
    unit: "metre",
    fee_amount: 10,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "SURVEYING_CHAIN",
    min_value: 20,
    max_value: 30,
    unit: "metre",
    fee_amount: 100,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "BEAM_SCALES_CLASS_A_B",
    min_value: 0,
    max_value: 0.5,
    unit: "kg",
    fee_amount: 60,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "BEAM_SCALES_CLASS_A_B",
    min_value: 1,
    max_value: 5,
    unit: "kg",
    fee_amount: 100,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "BEAM_SCALES_CLASS_A_B",
    min_value: 10,
    max_value: 50,
    unit: "kg",
    fee_amount: 150,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "BEAM_SCALES_CLASS_A_B",
    min_value: 100,
    max_value: 100,
    unit: "kg",
    fee_amount: 300,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "BEAM_SCALES_CLASS_A_B",
    min_value: 200,
    max_value: 200,
    unit: "kg",
    fee_amount: 400,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "BEAM_SCALES_CLASS_C_D",
    min_value: 0,
    max_value: 0.5,
    unit: "kg",
    fee_amount: 10,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "BEAM_SCALES_CLASS_C_D",
    min_value: 1,
    max_value: 5,
    unit: "kg",
    fee_amount: 15,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "BEAM_SCALES_CLASS_C_D",
    min_value: 10,
    max_value: 50,
    unit: "kg",
    fee_amount: 20,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "BEAM_SCALES_CLASS_C_D",
    min_value: 100,
    max_value: 200,
    unit: "kg",
    fee_amount: 100,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "BEAM_SCALES_CLASS_C_D",
    min_value: 300,
    max_value: 1000,
    unit: "kg",
    fee_amount: 200,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 0,
    max_value: 1,
    unit: "kg",
    fee_amount: 15,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 2,
    max_value: 15,
    unit: "kg",
    fee_amount: 30,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 20,
    max_value: 25,
    unit: "kg",
    fee_amount: 60,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 30,
    max_value: 200,
    unit: "kg",
    fee_amount: 100,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 250,
    max_value: 300,
    unit: "kg",
    fee_amount: 200,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 500,
    max_value: 1500,
    unit: "kg",
    fee_amount: 300,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 2000,
    max_value: 3000,
    unit: "kg",
    fee_amount: 400,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 5000,
    max_value: 5000,
    unit: "kg",
    fee_amount: 500,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 10000,
    max_value: 10000,
    unit: "kg",
    fee_amount: 1000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 15000,
    max_value: 150000,
    unit: "kg",
    fee_amount: 2000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 200000,
    max_value: 300000,
    unit: "kg",
    fee_amount: 3000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_MECHANICAL_CLASS_III_IV",
    min_value: 400000,
    max_value: 400000,
    unit: "kg",
    fee_amount: 4000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_ELECTRONIC_CLASS_III_IV",
    min_value: 0,
    max_value: 25,
    unit: "kg",
    fee_amount: 100,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_ELECTRONIC_CLASS_III_IV",
    min_value: 26,
    max_value: 300,
    unit: "kg",
    fee_amount: 200,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_ELECTRONIC_CLASS_III_IV",
    min_value: 301,
    max_value: 1500,
    unit: "kg",
    fee_amount: 250,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_ELECTRONIC_CLASS_III_IV",
    min_value: 1501,
    max_value: 3000,
    unit: "kg",
    fee_amount: 500,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_ELECTRONIC_CLASS_III_IV",
    min_value: 3001,
    max_value: 10000,
    unit: "kg",
    fee_amount: 1000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_ELECTRONIC_CLASS_III_IV",
    min_value: 10001,
    max_value: 150000,
    unit: "kg",
    fee_amount: 2000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_ELECTRONIC_CLASS_III_IV",
    min_value: 150001,
    max_value: 400000,
    unit: "kg",
    fee_amount: 3000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_CLASS_I_II",
    min_value: 0,
    max_value: 10,
    unit: "kg",
    fee_amount: 200,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_CLASS_I_II",
    min_value: 11,
    max_value: 50,
    unit: "kg",
    fee_amount: 250,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_CLASS_I_II",
    min_value: 51,
    max_value: 1000,
    unit: "kg",
    fee_amount: 500,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_CLASS_I_II",
    min_value: 1001,
    max_value: 10000,
    unit: "kg",
    fee_amount: 1000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_CLASS_I_II",
    min_value: 10001,
    max_value: 50000,
    unit: "kg",
    fee_amount: 2000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "NON_AUTOMATIC_WEIGHING_CLASS_I_II",
    min_value: 50001,
    max_value: null,
    unit: "kg",
    fee_amount: 3000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "AUTOMATIC_WEIGHING_INSTRUMENTS",
    min_value: 0,
    max_value: 10,
    unit: "kg",
    fee_amount: 200,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "AUTOMATIC_WEIGHING_INSTRUMENTS",
    min_value: 11,
    max_value: 50,
    unit: "kg",
    fee_amount: 250,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "AUTOMATIC_WEIGHING_INSTRUMENTS",
    min_value: 51,
    max_value: 1000,
    unit: "kg",
    fee_amount: 500,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "AUTOMATIC_WEIGHING_INSTRUMENTS",
    min_value: 1001,
    max_value: 10000,
    unit: "kg",
    fee_amount: 1000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "AUTOMATIC_WEIGHING_INSTRUMENTS",
    min_value: 10001,
    max_value: 50000,
    unit: "kg",
    fee_amount: 2000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "AUTOMATIC_WEIGHING_INSTRUMENTS",
    min_value: 50001,
    max_value: 100000,
    unit: "kg",
    fee_amount: 3000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "AUTOMATIC_WEIGHING_INSTRUMENTS",
    min_value: 100001,
    max_value: null,
    unit: "kg",
    fee_amount: 4000,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "DISPENSING_PUMPS",
    min_value: null,
    max_value: null,
    unit: "unit",
    fee_amount: 1000,
    fee_basis: "FIXED",
  },

  {
    state_code: "UP",
    category_code: "VOLUMETRIC_TOTALIZING_COUNTER",
    min_value: null,
    max_value: null,
    unit: "unit",
    fee_amount: 500,
    fee_basis: "FIXED",
  },

  {
    state_code: "UP",
    category_code: "VOLUMETRIC_OTHER_INSTRUMENTS",
    min_value: 0,
    max_value: 20,
    unit: "litre",
    fee_amount: 200,
    fee_basis: "FIXED",
  },

  {
    state_code: "UP",
    category_code: "VOLUMETRIC_OTHER_INSTRUMENTS",
    min_value: 21,
    max_value: 50,
    unit: "litre",
    fee_amount: 250,
    fee_basis: "FIXED",
  },

  {
    state_code: "UP",
    category_code: "VOLUMETRIC_OTHER_INSTRUMENTS",
    min_value: 51,
    max_value: 100,
    unit: "litre",
    fee_amount: 500,
    fee_basis: "FIXED",
  },

  {
    state_code: "UP",
    category_code: "FLOW_METERS",
    min_value: 0,
    max_value: 100,
    unit: "litre/min",
    fee_amount: 2000,
    fee_basis: "FIXED",
  },

  {
    state_code: "UP",
    category_code: "FLOW_METERS",
    min_value: 101,
    max_value: 500,
    unit: "litre/min",
    fee_amount: 3000,
    fee_basis: "FIXED",
  },

  {
    state_code: "UP",
    category_code: "FLOW_METERS",
    min_value: 501,
    max_value: null,
    unit: "litre/min",
    fee_amount: 5000,
    fee_basis: "FIXED",
  },

  {
    state_code: "UP",
    category_code: "TAXI_AUTO_RICKSHAW_METERS",
    min_value: null,
    max_value: null,
    unit: "unit",
    fee_amount: 100,
    fee_basis: "FIXED",
  },

  {
    state_code: "UP",
    category_code: "OTHER_LINEAR_METERS",
    min_value: 0,
    max_value: 1000,
    unit: "metre",
    fee_amount: 50,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "CLINICAL_THERMOMETER",
    min_value: null,
    max_value: null,
    unit: "unit",
    fee_amount: 0.5,
    fee_basis: "FIXED",
  },

  {
    state_code: "UP",
    category_code: "WATER_METER",
    min_value: null,
    max_value: null,
    unit: "unit",
    fee_amount: 25,
    fee_basis: "FIXED",
  },

  {
    state_code: "UP",
    category_code: "PEG_MEASURE",
    min_value: 30,
    max_value: 100,
    unit: "ml",
    fee_amount: 50,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "CNG_DISPENSERS",
    min_value: null,
    max_value: null,
    unit: "unit",
    fee_amount: 1000,
    fee_basis: "FIXED",
  },

  {
    state_code: "UP",
    category_code: "LPG_DISPENSERS",
    min_value: null,
    max_value: null,
    unit: "unit",
    fee_amount: 1000,
    fee_basis: "FIXED",
  },

  {
    state_code: "UP",
    category_code: "COUNTER_MACHINE",
    min_value: 0,
    max_value: 10,
    unit: "kg",
    fee_amount: 20,
    fee_basis: "PER_PIECE",
  },

  {
    state_code: "UP",
    category_code: "COUNTER_MACHINE",
    min_value: 11,
    max_value: null,
    unit: "kg",
    fee_amount: 50,
    fee_basis: "PER_PIECE",
  },
];

export const stateFees = [feeRules_MH, feeRules_UP];
